LuanRT/YouTube.js

lib/Constants.js

fixed this issue https://github.com/LuanRT/YouTube.js/issues/3

fixed x-goog-visitor-id for downloader

---

README.md

Replace colon with semicolon at the end of `fs` import statement.

docs: fix sample code for download example

---

lib/parser/ytmusic/search/AlbumResultItem.js
typings/lib/parser/ytmusic/search/AlbumResultItem.d.ts

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
- New feature (non-breaking change which adds functionality)

Album result support playlistId

---

lib/Innertube.js
lib/parser/contents/classes/Format.js
lib/parser/contents/classes/RichSection.js
lib/parser/contents/classes/SectionList.js
lib/parser/youtube/Library.js
lib/parser/youtube/VideoInfo.js
lib/parser/ytmusic/Search.js

As suggested in #45, this also implements a new "best" and
"bestefficiency" format selector.
@LuanRT please check that the new chooseFormat and download methods look ok. I've tested it on 2 videos and seems to work fine.

feat: download video directly from VideoInfo

---

package-lock.json
src/core/Session.ts
src/core/Studio.ts
src/utils/Constants.ts
src/utils/HTTPClient.ts

This adds support for uploading videos.
Related: #94

feat: add support for uploading videos

---

package-lock.json
package.json
src/parser/youtube/VideoInfo.ts

This reduces our bundle size from 909mb to 530mb

refactor: replace xmlbuilder2 with linkedom

---

examples/auth/README.md
examples/auth/index.js

Quick example for authentication. This was requested on Discord by @NFTLAD#0861

docs: OAuth example

---

src/parser/classes/NavigationEndpoint.ts
src/parser/index.ts

1. In `NavigationEndpoint`, add `params` to `watch_playlist`
2. In `Parser`, fix possible empty continuation in `PlaylistPanelContinuation`

Minor fixes

---

docs/API/music.md
src/core/Actions.ts
src/core/Music.ts
src/parser/classes/Element.ts
src/parser/classes/HighlightsCarousel.ts
src/parser/classes/MusicElementHeader.ts
src/parser/classes/MusicLargeCardItemCarousel.ts
src/parser/classes/NavigationEndpoint.ts
src/parser/map.ts
src/parser/youtube/Analytics.ts
src/parser/ytmusic/Playlist.ts
src/parser/ytmusic/Recap.ts

This PR aims to add support for YouTube Music's latest feature; recap.
Related: #163

feat: add `music#getRecap()`

---

src/core/Music.ts
src/parser/classes/DropdownItem.ts
src/parser/ytmusic/Artist.ts

2 fixes:
- `Music#getArtist()` for private artist IDs
- Inconsistent prop name in `DropdownItem` (CamelCase used for `iconType`, when it should be `icon_type`)

Fixes for `Music#getArtist()` and `DropdownItem`

---

package-lock.json
package.json
src/core/Player.ts

Improve signature decipher extraction, the way we were doing it before was too error prone. And also update Jinter to v0.2.0.

fix: improve sig extraction

---

index.ts

Fixes “ReferenceError: ReadableStream is not defined”.

added missing import in index.ts

---

src/parser/classes/ConfirmDialog.ts
src/parser/classes/MetadataScreen.ts
src/parser/classes/PlayerErrorMessage.ts
src/parser/classes/SubscribeButton.ts
src/parser/classes/VideoSecondaryInfo.ts
src/parser/index.ts
src/parser/map.ts

Minor fixes and improvements.
Closes #192

fix: minor parsing issues and other improvements 

---

examples/browser/README.md
examples/browser/proxy/deno.ts

Quick update to the browser example.

fix: browser example

---

package-lock.json
package.json
src/core/Session.ts
src/utils/HTTPClient.ts

fix: include `thirdParty` prop for requests using `TV_EMBEDDED`

---

CONTRIBUTING.md
docs/updating-the-parser.md
src/parser/README.md
src/parser/index.ts

This adds instructions on how to implement new renderer parsers, fixes typos and other minor documentation improvements.

docs: add parser ytnode instructions & other minor changes

---

src/parser/index.ts

The wrong element is fetched. See #216
Fixes #216

fix: wrong element name

---

src/parser/classes/WatchCardHeroVideo.ts
test/constants.ts
test/main.test.ts

Any search query that needs to parse a WatchCardHeroVideo is currently broken.
Fixes #230

fix: WatchCardHeroVideo accessibilityData parse error

---

src/parser/classes/HorizontalCardList.ts
src/parser/classes/RichListHeader.ts
src/parser/classes/Shelf.ts
src/parser/classes/UniversalWatchCard.ts
src/parser/classes/VerticalWatchCardList.ts
src/parser/classes/Video.ts
src/parser/classes/WatchCardHeroVideo.ts
src/parser/classes/WatchCardRichHeader.ts
src/parser/classes/WatchCardSectionSequence.ts
src/parser/youtube/Library.ts
src/parser/youtube/Search.ts

Refactor search parser to use memo to get `YTNodes` and fix minor parsing errors.

refactor: improve Search parser

---

src/parser/classes/livechat/items/LiveChatRestrictedParticipation.ts
src/parser/map.ts

feat: add `LiveChatRestrictedParticipation` node

---

examples/comments/Comment.md
examples/comments/CommentThread.md
examples/comments/README.md
examples/comments/index.ts
src/parser/classes/ContinuationItem.ts
src/parser/classes/EmojiPickerCategory.ts
src/parser/classes/EmojiPickerCategoryButton.ts
src/parser/classes/EmojiPickerUpsellCategory.ts
src/parser/classes/SortFilterSubMenu.ts
src/parser/classes/comments/Comment.ts
src/parser/classes/comments/CommentActionButtons.ts
src/parser/classes/comments/CommentDialog.ts
src/parser/classes/comments/CommentReplies.ts
src/parser/classes/comments/CommentReplyDialog.ts
src/parser/classes/comments/CommentSimplebox.ts
src/parser/classes/comments/CommentThread.ts
src/parser/classes/comments/CommentsHeader.ts
src/parser/classes/comments/CreatorHeart.ts
src/parser/classes/comments/EmojiPicker.ts
src/parser/classes/comments/PdgCommentChip.ts
src/parser/classes/comments/SponsorCommentBadge.ts
src/parser/classes/misc/EmojiRun.ts
src/parser/index.ts
src/parser/map.ts
src/parser/youtube/Comments.ts
src/parser/youtube/ItemMenu.ts
src/proto/index.ts
test/main.test.ts

This improves parsing in all nodes related to the comment section, implements missing properties and adds new functionality such as sorting the comment section using an existing `Comments` object. 
A few examples:
```ts
(async () => {
// Sort comment section using an existing 'Comments' object:
const comment_section = await yt.getComments('somevideoid');
const sorted_comments = await comment_section.applySort('NEWEST_FIRST');
console.log(sorted_comments); 
// This PR also includes a fix for the comment translation method:
const top_thread = comment_section.contents.first();
const translated_comment = await …
```

feat: finalize comment section nodes 

---

src/parser/index.ts
src/parser/youtube/LiveChat.ts
src/parser/youtube/SmoothedQueue.ts

Inproves live chat poll timing (especially for live chats with thousands of participants) and error handling.

refactor: improve live chat polling and error handling

---

docs/API/kids.md
src/core/Feed.ts
src/core/Kids.ts
src/parser/classes/ItemSection.ts
src/parser/index.ts
src/parser/ytkids/Channel.ts
test/constants.ts
test/main.test.ts

Should've been added by #291, but unfortunately I completely forgot about it : ).
```ts
(async () => {
const channel = await yt.kids.getChannel('UCpbpfcZfo-hoDAx2m1blFhg');
console.log(channel);
})();
```

feat(ytkids): add `kids#getChannel()`

---

src/parser/youtube/Channel.ts

Adds a missing "?" which will allow getting the continuation of the community tab
Fixes #328 

fix getting community continuations

---

src/parser/classes/Shelf.ts

feat(parser): Add `play_all_button` to `Shelf`

---

src/parser/classes/MusicCardShelf.ts
src/parser/classes/MusicCardShelfHeaderBasic.ts
src/parser/map.ts
src/parser/ytmusic/Search.ts

Adds support for the new shelf introduced by YouTube Music this week:

feat(parser): add `MusicCardShelf`

---

src/parser/classes/MusicResponsiveListItem.ts
src/parser/classes/MusicTastebuilderShelf.ts
src/parser/classes/MusicTastebuilderShelfThumbnail.ts
src/parser/nodes.ts
src/parser/ytmusic/HomeFeed.ts
src/utils/Utils.ts

Adds `MusicTastebuilderShelf` and `MusicTastebuilderShelfThumbnail`. These usually appear on new accounts.

feat(ytmusic): add taste builder nodes

---

src/utils/Utils.ts

Fixes PR #398
Erm so yeah turns out i created a circular dependency and webpack can't handle it in development mode🙈 (this works now)

fix(Utils): Circular dependency introduced in 38a83c3c2aa814150d1d9b8ed99fca915c1d67fe

---

src/utils/Constants.ts

Update the web client version to the latest one.

chore(constants): Update web client version

---

src/parser/classes/CarouselLockup.ts
src/parser/classes/EngagementPanelSectionList.ts
src/parser/classes/EngagementPanelTitleHeader.ts
src/parser/classes/ExpandableVideoDescriptionBody.ts
src/parser/classes/Factoid.ts
src/parser/classes/InfoRow.ts
src/parser/classes/StructuredDescriptionContent.ts
src/parser/classes/VideoDescriptionHeader.ts
src/parser/classes/VideoDescriptionInfocardsSection.ts
src/parser/classes/VideoDescriptionMusicSection.ts
src/parser/generator.ts
src/parser/nodes.ts
src/parser/youtube/VideoInfo.ts

Fixes some parser issues introduced in a recent PR.
Closes #426

fix: incorrect node parser implementations

---

src/parser/classes/misc/Format.ts

This reduces some of the duplicate work that is currently done when the xtags are parsed. Additionally this slightly reduces the bundle size.

perf(Format): Cleanup the xtags parsing

---

src/parser/classes/HashtagTile.ts
src/parser/nodes.ts

This is used for search results (ex: searching "#meow" should have a HashtagTile in the results).
See https://github.com/FreeTubeApp/FreeTube/pull/3483#issuecomment-1537516380

feat(parser): Add `HashtagTile`

---

src/parser/parser.ts

This node usually shows up in the home feed if you have a premium subscription.

feat(parser): Add `ShowMiniplayerCommand`

---

src/parser/classes/IncludingResultsFor.ts
src/parser/nodes.ts

This PR adds parsing support for `IncludingResultsFor` which usually appears when there's a typo in the search

feat(parser): Add `IncludingResultsFor`

---

src/parser/classes/AlertWithButton.ts
src/parser/nodes.ts
src/parser/parser.ts
src/parser/types/ParsedResponse.ts

Appears on playlists that have unavailable videos e.g. https://youtube.com/playlist?list=PLa4zmfXkL4P0RkofW6vbsqhOAKgjwLws1.

feat(parser): Add `AlertWithButton`

---

src/parser/classes/CompactMovie.ts
src/parser/nodes.ts

They appear in the watch next feed next to film trailers e.g. https://youtu.be/pBk4NYhWNMM

feat(parser): Add `CompactMovie`

---

src/parser/classes/CompactMovie.ts

fix(CompactMovie): Add missing import and remove unnecessary console.log

---

src/parser/classes/ChannelMetadata.ts

Shows up on auto-generated artist topic channels like Adele: https://www.youtube.com/channel/UCRw0x9_EfawqmgDI2IgQLLg

feat(ChannelMetadata): Add `music_artist_name`

---

docs/updating-the-parser.md
examples/auth/index.js

chore(docs): Minor update

---

src/parser/classes/FeedNudge.ts
src/parser/nodes.ts

see https://github.com/LuanRT/YouTube.js/actions/runs/6679090140/job/18150827068?pr=532

feat: add `FeedNudge`

---

src/core/Player.ts
src/parser/classes/misc/Author.ts

This pull request removes one unused private property (I accidentally committed it in https://github.com/LuanRT/YouTube.js/pull/505) and converts another one to a local variable, as it is only used in the constructor.

chore: Clean up some unneeded private properties

---

src/Innertube.ts
src/core/Actions.ts

Add an API to get the feed of channels (`FEchannels`)
Fixes #63

feat(YouTube): Add FEchannels feed

---

src/core/OAuth.ts

Fixes https://github.com/LuanRT/YouTube.js/issues/564.

feat(OAuth): Allow passing custom OAuth2 client creds

---

src/parser/classes/ItemSection.ts
src/parser/classes/SortFilterHeader.ts
src/parser/nodes.ts
src/parser/youtube/Settings.ts

fix(Parser): add SortFilterHeader

---

src/parser/classes/PlayerMicroformat.ts
src/parser/youtube/VideoInfo.ts

Appears on live stream replays.

feat(VideoInfo): Add live stream `end_timestamp`

---

src/parser/classes/misc/Format.ts

feat(Format): Add `max_dvr_duration_sec` and `target_duration_dec`

---

src/parser/classes/misc/VideoDetails.ts

feat(VideoDetails): Add `is_live_dvr_enabled`, `is_low_latency_live_stream` and `live_chunk_readahead`

---

src/parser/classes/AvatarView.ts
src/parser/classes/DecoratedAvatarView.ts

Fixes the parsing and handling of optional properties in `DecoratedAvatarView` and it's child `AvatarView`.

fix(DecoratedAvatarView): Fix parsing and optional properties

---

src/platform/web.ts

fix(Cache): handle the value read from the db correctly according to its type

---

src/parser/classes/comments/CommentView.ts

This PR removes some unused test code

Remove test code

---

src/parser/classes/misc/Format.ts

Test video: https://youtu.be/cCEK6XrcUx0

feat(Format): Add `spatial_audio_type`

---

src/parser/classes/ItemSection.ts

A fix that was made in #638 but PR is closed

Item section target_id fix

---

src/parser/parser.ts

fix(parser): ignore MiniGameCardView node

---

src/parser/parser.ts

feat(parser): add classdata to unhandled parse errors

---

src/parser/classes/StructuredDescriptionContent.ts
src/parser/classes/VideoAttributesSectionView.ts
src/parser/nodes.ts

closes #726
Unfortunately I'm not able to reproduce this consistently, even with the same visitor data, so this is based on the generator output and I haven't been able to test it.

feat(parser): Add `VideoAttributesSectionView` node

---

src/parser/classes/ThumbnailOverlayResumePlayback.ts

fix(ThumbnailOverlayResumePlayback): Update `percent_duration_watched` type

---

src/parser/classes/ItemSection.ts

fix(ItemSection): FeedFilterChipBar parse error

---

examples/browser/web/package-lock.json
examples/browser/web/package.json
examples/browser/web/src/main.ts

This refactors the browser example to use Google's UMP for video streaming.

chore(examples/web): Use `UMP`

---

src/utils/DashManifest.tsx

Tested by a discord user.
I also tested that it still works with shaka-player.

fix(toDash): Fix dash.js 4.x compatibility

---

src/parser/classes/ShortsLockupView.ts

fix(parser): Fix ShortsLockupView assuming that the primary text always exists

---

src/parser/classes/misc/Format.ts
src/utils/StreamingInfo.ts

Example video: https://youtu.be/snZ9w5xc_ic

feat: Support auto-dubbed audio tracks

---

src/parser/classes/AccountItem.ts

This PR adds `channel_handle` to `AccountItem`
Example response from latest `AccountListEndpoint`. It has new property called `channelHandle`.
```json
{
"contents": [
{
"accountItemSectionRenderer": {
"contents": [
{
"accountItem": {
"accountName": { "simpleText": "<Account Name>" },
"accountPhoto": {
{
"url": "<URL>",
"width": 216,
"height": 216
}
]
},
"isSelected": true,
"isDisabled": false,
"hasChannel": true,
"serviceEndpoint": {
"selectActiveIdentityEndpoint": {
"supportedTokens": [
{ "accountStateToken": { "hasChannel": true, "isMerged": true, "obfuscatedGaiaId": "<obfuscatedGaiaId>" } },
{ "offlineCacheKeyToken": { "clientCacheKey": "<clientCacheKey>" } },
{ "datasyncIdToken": { "datasyncIdToken": "<datasyncIdToken>" } }
]
}
},
"accountByline": { "simpleText": …
```

feat(account): add `channel_handle` to `AccountItem`

---

src/parser/classes/VideoCard.ts

VideoCard has a few minor differences from the Video class.
This PR properly handles those differences.
This can be tested by making a request to: https://www.youtube.com/gaming
and getting the Trending Videos shelf

fix(VideoCard): fix parsing author, view count and published date

---

src/parser/classes/livechat/items/LiveChatBannerRedirect.ts
src/parser/nodes.ts

Add a new parser for the live chat node that appears when a streamer redirects their viewers to another channel’s live stream.
```json
{
"liveChatBannerRedirectRenderer": {
"bannerMessage": {
"runs": [
{
"text": "Don't miss out! People are going to watch something from ",
"textColor": 4294967295,
"fontFace": "FONT_FACE_ROBOTO_REGULAR"
},
{
"text": "洛可洛斯特Loco Lost",
"bold": true,
"textColor": 4294967295,
"fontFace": "FONT_FACE_ROBOTO_REGULAR"
}
]
},
{
"url": "https://yt4.ggpht.com/ytc/AIdro_nIvJCRqMHTDI2MJ74WX4bOCARktdMS6uHDR4TDh7Y7LA=s32-c-k-c0x00ffffff-no-rj",
"width": 32,
"height": 32
},
{
"url": "https://yt4.ggpht.com/ytc/AIdro_nIvJCRqMHTDI2MJ74WX4bOCARktdMS6uHDR4TDh7Y7LA=s64-c-k-c0x00ffffff-no-rj",
"width": 64,
"height": 64
}
] …
```

feat(parser): Add `LiveChatBannerRedirect` node

---

src/parser/classes/livechat/items/LiveChatBannerChatSummary.ts
src/parser/classes/misc/TextRun.ts
src/parser/nodes.ts

```json
{
"liveChatBannerChatSummaryRenderer": {
"liveChatSummaryId": "gKonxsPlU-M_1731888622579899",
"chatSummary": {
"runs": [
{
"text": "Chat summary",
"bold": true,
"fontFace": "FONT_FACE_ROBOTO_MEDIUM"
},
{
"text": "\n"
},
{
"text": "Auto-generated experiment • Quality may vary",
"deemphasize": true,
"fontFace": "FONT_FACE_ROBOTO_MEDIUM"
},
{
"text": "\n"
},
{
"text": "Viewers in the chat are discussing their favorite Final Fantasy games, ranging from Final Fantasy X to Final Fantasy XIII. They are also requesting songs from various artists, including Keshi, Chapel Roan, Sanae, and others.",
"fontFace": "FONT_FACE_ROBOTO_REGULAR"
}
]
},
"icon": {
"iconType": "SPARK"
},
"trackingParams": "CB8Q77sMIhMIidfw9MvkiQMVcNpMAh1jfgrU",
"likeFeedbackButton": { …
```

feat(parser): Add `LiveChatBannerChatSummary` node, update `TextRun` node

---

src/core/Player.ts

https://www.youtube.com/s/player/5b77d519/player_ias.vflset/en_US/base.js

fix(Player): Fix signature algorithm extraction again

---

src/parser/classes/livechat/items/LiveChatMembershipItem.ts

This PR updates the `LiveChatMembershipItem` to parse the additional fields.
```json
{
"liveChatMembershipItemRenderer": {
"id": "ChwKGkNJZWUxNlNqMVBZQ0ZmOElyUVlkZjhVRzhn",
"timestampUsec": "1647765085456245",
"timestampText": {
"simpleText": "-30:09"
},
"authorExternalChannelId": "UCsdJqYo7golpSd_pcVFX64w",
"headerSubtext": {
"runs": [
{
"text": "Welcome to "
},
{
"text": "初ㄐㄐ貓草"
},
{
"text": "!"
}
]
},
"simpleText": "貝希茸 Beheron"
},
{
"url": "https://yt4.ggpht.com/cb55K743FS36sqCuSN2C0Zfad1A-0sd6luHHG3_4VT-8lhCGIpXusya_wA6aXQKLbnZh3wbWuA=s32-c-k-c0x00ffffff-no-rj",
"width": 32,
"height": 32
},
{
"url": "https://yt4.ggpht.com/cb55K743FS36sqCuSN2C0Zfad1A-0sd6luHHG3_4VT-8lhCGIpXusya_wA6aXQKLbnZh3wbWuA=s64-c-k-c0x00ffff …
```

feat(parser): Update `LiveChatMembershipItem`

---

src/parser/classes/livechat/items/LiveChatTickerPaidMessageItem.ts

This PR updates the `LiveChatTickerPaidMessageItem` parser:
* Change `duration_sec` property type from `string` to `number`
* Change `full_duration_sec` property type from `string` to `number`
* Handle the scenario where the author's name is represented as `authUsername`
* Mark `amount` property as optional
* Add `start_background_color` property
* Add `amount_text_color` property
* Add `end_background_color` property
* Add `animation_origin` property
* Add `open_engagement_panel_command` property
```json
{
"liveChatTickerPaidMessageItemRenderer": {
"id": "ChwKGkNJYnV3cG1NenZvQ0ZWM0R3Z1FkN1owQ25B",
"amountTextColor": 3758096383,
"startBackgroundColor": 4294278144,
"endBackgroundColor": 4293284096,
{
"url": …
```

feat(parser): Update `LiveChatTickerPaidMessageItem`

---

src/parser/classes/livechat/items/CreatorHeartView.ts
src/parser/classes/livechat/items/LiveChatPaidMessage.ts
src/parser/classes/livechat/items/PdgReplyButtonView.ts
src/parser/nodes.ts

This PR updates the `LiveChatPaidMessage` parser:
* Add `author_name_text_color` property
* Add `context_menu_accessibility_label` property
* Add `timestamp_usec` property
* Mark `timestamp_text` property as optional
* Add `timestamp_color` property
* Add `text_input_background_color` property
* Add `creator_heart_button` property
* Add `is_v2_style` property
* Add `reply_button` property
```json
{
"liveChatPaidMessageRenderer": {
"id": "ChwKGkNKMjByTlNKenZvQ0ZmUVo1d29kZFc4TEdB",
"timestampUsec": "1665144247876066",
"simpleText": "天野よなく"
},
{
"url": "https://yt4.ggpht.com/ytc/AIdro_l49U75p-6oIHx0Zd5WW1LvI1OeNpW06pFYyL-rTCNm6b4=s32-c-k-c0x00ffffff-no-rj",
"width": 32,
"height": 32
},
{
"url": …
```

feat(parser): Update `LiveChatPaidMessage`

---

src/parser/classes/livechat/items/LiveChatTickerPaidStickerItem.ts

The `LiveChatTickerPaidStickerItem` class has been updated to extend `YTNode` instead of `LiveChatTickerPaidMessageItem` to better align with the latest data provided by InnerTube
```json
{
"liveChatTickerPaidStickerItemRenderer": {
"id": "ChwKGkNPNmI3ZW5CcUlvREZVdkV3Z1FkNlFZVDJR",
{
"url": "https://yt4.ggpht.com/ytc/AIdro_lmdU1tg3poJ8X_t8MFGZpZD-7nFujvA6blC4MIv7QIOBY=s32-c-k-c0x00ffffff-no-rj",
"width": 32,
"height": 32
},
{
"url": "https://yt4.ggpht.com/ytc/AIdro_lmdU1tg3poJ8X_t8MFGZpZD-7nFujvA6blC4MIv7QIOBY=s64-c-k-c0x00ffffff-no-rj",
"width": 64,
"height": 64
}
],
"accessibility": {
"accessibilityData": {
"label": "八神光"
}
}
},
"startBackgroundColor": 4294953512,
"endBackgroundColor": 4294947584,
"durationSec": 300, …
```

feat(parser): Update `LiveChatTickerPaidStickerItem`

---

src/parser/classes/Button.ts

This PR updates the `Button` parser:
* Add `style` property
* Add `size` property
* Add `target_id` property
* Parse `data.accessibilityData.accessibilityData.label` if `data.accessibility.label` is unavailable
```json
{
"buttonRenderer": {
"style": "STYLE_BLUE_TEXT",
"size": "SIZE_DEFAULT",
"isDisabled": false,
"text": {
"simpleText": "Learn more"
},
"navigationEndpoint": {
"clickTrackingParams": "CB8Q8FsiEwiE3dTgramKAxXD1UwCHcXaFsg=",
"commandMetadata": {
"webCommandMetadata": {
"url": "//support.google.com/youtube/?p=subs_only_chat_viewer&hl=en",
"webPageType": "WEB_PAGE_TYPE_UNKNOWN",
"rootVe": 83769
}
},
"urlEndpoint": {
"url": "//support.google.com/youtube/?p=subs_only_chat_viewer&hl=en",
"target": "TARGET_NEW_WINDOW"
}
},
"trackingParams": …
```

feat(parser): Update `Button`

---

src/parser/classes/livechat/items/LiveChatViewerEngagementMessage.ts

Update `LiveChatViewerEngagementMessage` to extend `YTNode` rather than `LiveChatMessageBase` to better align with the latest data provided by Innertube.
```json
{
"liveChatViewerEngagementMessageRenderer": {
"id": "Ci0KK1NVQlNDUklCRVJTX09OTFlfVkVNMjAyNC8xMi8xNS0wMDoyOToxNi45ODc%3D",
"timestampUsec": "1734251356987117",
"icon": {
"iconType": "YOUTUBE_ROUND"
},
"message": {
"runs": [
{
"text": "Subscribers-only mode. Messages that appear are from people who’ve subscribed to this channel for "
},
{
"text": "1 minute"
},
{
"text": " or longer."
}
]
},
"actionButton": {
"buttonRenderer": {
"style": "STYLE_BLUE_TEXT",
"size": "SIZE_DEFAULT",
"isDisabled": false,
"text": {
"simpleText": "Learn more"
},
"navigationEndpoint": {
"clickTrackingParams": …
```

feat(parser): Update `LiveChatViewerEngagementMessage`

---

src/core/managers/PlaylistManager.ts

Adds the possibility to add a external playlist to a user library.
Worked as sharm with v11, I adapted it to v12 structure. :)

feat(Playlists): Implement `addToLibrary` and `removeFromLibrary`

---

src/parser/classes/livechat/items/LiveChatPaidSticker.ts

This PR updates the `LiveChatPaidSticker` parser:
* Add `sticker_accessibility_label` property
* Add `sticker_display_width` property
* Add `sticker_display_height` property
* Add `context_menu_accessibility_label` property
* Add `timestamp_usec` property
* Add `is_v2_style` property
```json
{
"liveChatPaidStickerRenderer": {
"id": "ChwKGkNPNmI3ZW5CcUlvREZVdkV3Z1FkNlFZVDJR",
"contextMenuEndpoint": {
"clickTrackingParams": "CAUQ77sEIhMIwc_N8cGoigMV_-1MAh2NTwkk",
"commandMetadata": {
"webCommandMetadata": {
"ignoreNavigation": true
}
},
"liveChatItemContextMenuEndpoint": {
"params": "Q2g0S0hBb2FRMDgyWWpkbGJrSnhTVzlFUmxWMlJYZG5VV1EyVVZsVU1sRWFLU29uQ2hoVlEzbHJaMEYxU1dwdU56QmZRMWhNVG1wYU9IcHdjRkVTQzBSQ1NHNXJPSGRxT0VwaklBRW9CRElhQ2hoVlF6SkZhVjh6VW5KdlpHczVUMkpxYUVSelVVMVd …
```

feat(parser): Update `LiveChatPaidSticker`

---

src/parser/youtube/Channel.ts

Add support for channel course tab. 
Ex: https://www.youtube.com/@InfinityLearn_NEET/courses

feat(Channel): Add `getCourses` method

---

src/utils/FormatUtils.ts

Sorry, I made a mistake in #884 . `itag` is unique and with highest priority.
cc @LuanRT

fix(FormatUtils): itag matching

---

README.md

Currently, deno support install npm package

docs(installation): add install command for deno

---

src/core/managers/PlaylistManager.ts

This fixes the following error:
```
This playlist type is unviewable.
```

fix(PlaylistManager): Playlist ID

---

src/parser/classes/DialogView.ts

This fixes the following:
```
Type mismatch, got PanelFooterView expected FormFooterView.
```

fix(Parser): Type mismatch

---

src/parser/youtube/Playlist.ts

Fixes #800.
It looks like the workaround introduced in #801 was later reversed in 7397aa3f. If this gets merged, the changes in 49f54dc could be used if desired.

fix(Playlist): is_editable

---

package-lock.json
package.json
src/core/Player.ts
src/utils/Utils.ts

The new `findVariable` searches for the variable declaration using an AST walker. 
Tested with the following player scripts:
https://www.youtube.com/s/player/643afba4/player_ias.vflset/en_US/base.js https://www.youtube.com/s/player/4fcd6e4a/player_ias.vflset/en_US/base.js https://www.youtube.com/s/player/363db69b/player_ias.vflset/en_US/base.js
Closes #928

fix(Player): Parse global variable used by nsig/sig

---

src/utils/HTTPClient.ts

fix(HTTPClient): Use the correct constant for the iOS client OS name

---

src/parser/classes/OpenOnePickAddVideoModalCommand.ts
src/parser/nodes.ts

feat(Parser): Add `OpenOnePickAddVideoModalCommand` node

---

src/core/Actions.ts

May help with #965, even if it doesn't it is still a worthwhile clean up in my mind.

refactor(Actions): Use Response.json instead of JSON.parse + Response.text

---

src/parser/ytmusic/Artist.ts

The getAllSongs() method was giving an error. I believe the cause of this is YouTube renaming the section from "Songs" to "Top songs". So I changed the condition for the checking the getAllSongs() method. And now it works for me.

fix(Artist): `getAllSongs` not finding target shelf

---

src/parser/classes/ToggleFormField.ts
src/parser/nodes.ts

feat(Parser): Add `ToggleFormField` node

---

src/Innertube.ts

e.g. `UCp9SaHDXdBaXu7EuMZWExMg` redirects to `UCPZwSTQmoMlHRNA8iN0syOA`

fix(Innertube): Handle redirects in getChannel()
