LuanRT/YouTube.js

lib/Constants.js

The playerResponse streamingData adaptiveFormats are filtered to include only those which
include a qualityLabel. This array is then mapped to an array of qualityLabels and sorted
from lowest to highest quality. A Set is created then spread syntax is used to remove duplicates.

Include available video qualities to metadata

---

lib/Innertube.js
lib/core/OAuth.js
lib/core/Player.js
lib/core/SessionBuilder.js
lib/utils/Request.js

Axios instance now shared between modules and allows to use http(s) and socks proxy per instance.
Socks5 proxy: 
```Javascript
import Innertube from 'youtubei.js';
import { SocksProxyAgent } from 'socks-proxy-agent';
const youtube = await new Innertube({ gl: 'US', httpsAgent: new SocksProxyAgent('socks5://your.proxy.url:port') });
```
http/https proxy: 
```Javascript
import Innertube from 'youtubei.js';
const youtube = await new Innertube({
gl: 'US',
proxy: {
protocol: 'https',
host: '127.0.0.1',
port: 9000,
auth: {
username: 'mikeymike',
password: 'rapunz3l'
}
)
});
```
Fixes #60 

Socks and http(s) proxy support for each session

---

examples/index.js
lib/parser/youtube/VideoInfo.js

This commit is mainly to fix the best video format selection problem, when a video exists in 2160p format, it may not be in mp4 format, which causes the best_width to hit 4096, but this video format does not enter candidates.
Finally chooseFormat will return an undefined.
You can use the following video id to recreate the situation
``` javascript
// Downloading videos:
const stream = youtube.download("p--VpPCwp9Q", {
format: 'mp4', // Optional, ignored when type is set to audio and defaults to mp4, and I recommend to leave it as it is
quality: 'best', // if a video doesn't have a specific quality it'll fall back to 360p, this is ignored when type is set to audio
type: 'video' // can be “video”, “audio” and “videoandaudio”
});
```
Fixes # (issue)
Please delete options that are not …

 fix(VideoInfo): Fix the problem that chooseFormat still returns empty, even though there are videos to adapt

---

lib/parser/contents/classes/MusicResponsiveListItem.js
typings/lib/parser/contents/classes/MusicResponsiveListItem.d.ts

I've extended my previous PR (#82) to the new parser. YT Music videos can also have multiple authors, so I added the `authors` key. However, I'm unsure about removing `author` - I kept it there, returning the first item of `authors`.

feat(contents): Multiple video authors

---

src/core/Studio.ts

Small TS type change to allow for uploading any `BodyInit` which allows uploading from a ReadableStream or File instead of reading the whole file into memory first.

refactor: allow uploads of streams

---

src/core/OAuth.ts
src/core/Session.ts

Use `UniversalCache` instance to cache user credentials
Opt-in via `OAuth#cacheCredentials()`. `OAuth#init()` will check the cache before starting the OAuth flow.

feat: allow users to cache OAuth credentials

---

src/parser/classes/DropdownItem.ts
src/parser/classes/MusicDetailHeader.js
src/parser/classes/MusicEditablePlaylistDetailHeader.ts
src/parser/classes/MusicShelf.ts
src/parser/index.ts
src/parser/map.ts
src/parser/ytmusic/Playlist.ts

Fixes:
- Parsing error with headers of own / self-created playlists
Adds:
- `music#Playlist.getSuggestions()`
-----------------
- `refresh`: <boolean>. if `true`, returns a new list of suggestions. Otherwise, returns the last-fetched result. Default: `true`.
An empty array is returned if no suggestions are available. It seems that suggestions are not provided for long playlists.
E.g.:
```
const playlist = await youtube.music.getPlaylist(playlist_id);
const suggestions = await playlist.getSuggestions(); // Returns array of suggested items
// Calling `getSuggestions()` again will return a *new* list of items
const suggestions2 = await playlist.getSuggestions();
// To get the last fetched list of suggestions, call `getSuggestions(false)`
const suggestions3 = await …
```

feat(ytmusic): `music#Playlist` fixes and additions

---

src/parser/classes/Grid.js
src/parser/classes/GridHeader.ts
src/parser/classes/MusicHeader.js
src/parser/classes/MusicResponsiveListItem.ts
src/parser/classes/MusicTwoRowItem.js
src/parser/map.ts

- Parse and include `header` field, if available.
- Parse and include `title` field, if available.
- Add `subtitle` field to `MusicResponsiveListItem` for consistency with `MusicTwoRowItem`.
- Better parsing of `subscribers` value. It is usually available, but not always. If available, it is not always contained in `text.runs[2]`.
- Add `song_count` field, although it is usually unavailable (I can only see it in Library artists).

Misc fixes and additions

---

src/parser/classes/MusicDetailHeader.js
src/parser/classes/MusicResponsiveListItem.ts

2 minor commits:
1. In `MusicResponsiveListItem`, get video duration from `fixed_columns` if not found in `flex_columns`
2. In `MusicDetailHeader`, guard against parser from throwing error when `total_duration` is not available (such as when parsing header of "Your Likes" playlist which doesn't show duration info)

feat: improve parsing

---

src/parser/classes/PlaylistPanel.ts

1. Fix possible content type mismatch due to introduction of `AutomixPreviewVideo`.
2. Fix parse error when no continuation is available.

`PlaylistPanel` fixes

---

src/parser/classes/MusicTwoRowItem.ts

Playlist radios are items (`MusicTwoRowItem`) that contain only a 'watch playlist' endpoint. I encountered them in the Home Feed of ytmusic. When a playlist radio is clicked, ytmusic starts playing from the playlist referred to by the watch endpoint. This PR fixes the situation where playlist radios are misidentified as videos.
Also a bit of refactoring done in the process to `MusicTwoRowItem`.

fix: playlist radios misidentified as videos

---

src/parser/index.ts
test/main.test.ts

video info captions is an empty SuperParsedResult, it should be a PlayerCaptionsTracklist in order to parse properly.
Fixes # (issue)
N/A
- [N/A ] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the documentation

fix: captions should be a PlayerCaptionsTracklist

---

src/core/Music.ts
src/parser/classes/IconLink.ts
src/parser/classes/MusicCarouselShelfBasicHeader.ts
src/parser/map.ts

2 commits:
1. Add `end_icons` field to `MusicCarouselShelfBasicHeader` (array of `IconLink` - similar to `Button` with endpoint).
2. Fix `music#getPlaylist()`. The current implementation strips *all* occurrences of 'VL' from `playlist_id` and then adds one to the beginning. This breaks fetching for `playlist_id` that contains 'VL' not at the beginning, but somewhere after that.

Add `end_icons` to `MusicCarouselShelfBasicHeader` and fix `music#getPlaylist()`

---

src/core/Actions.ts
src/parser/classes/MusicDetailHeader.ts
src/parser/classes/MusicShelf.ts
src/parser/classes/MusicSideAlignedItem.ts
src/parser/classes/MusicSortFilterButton.ts
src/parser/classes/MusicTwoRowItem.ts
src/parser/classes/NavigationEndpoint.ts
src/parser/classes/menus/MusicMenuItemDivider.ts
src/parser/classes/menus/MusicMultiSelectMenu.ts
src/parser/classes/menus/MusicMultiSelectMenuItem.ts
src/parser/index.ts
src/parser/map.ts

A `MusicSortFilterButton` pulls up a menu much like a dropdown. Example of one is the country selector found on YouTube Music -> Explore -> Charts. The following code illustrates usage of `MusicSortFilterButton`:
```
// Endpoint for YouTube Music Charts page
const endpoint = new NavigationEndpoint({
browseEndpoint: {
browseId: 'FEmusic_charts'
}
});
const fetchAndPrint = async (endpoint) => {
console.log('Fetching Charts...')
const response = await endpoint.call(youtube.actions, 'YTMUSIC');
const page = Parser.parseResponse(response.data);
const sections = page.contents_memo.getType(SectionList)?.[0]?.contents?.array() || [];
console.log('Got the following sections:');
console.log(JSON.stringify(sections));
return page;
}
const page = await fetchAndPrint(endpoint);
// The Charts page …
```

feat: add `MusicSortFilterButton`

---

src/parser/classes/MusicResponsiveListItem.ts
src/parser/classes/MusicShelf.ts
src/parser/classes/MusicTwoRowItem.ts
src/parser/ytmusic/Library.ts

Kind of fixes #143 by returning items with `item_type` of  'library_artist'  instead of 'artist'. Items of this type have an `endpoint` that leads to a page listing of the artist's songs (equivalent to clicking an artist in Library -> Artists). I think, at this stage, it would have to be up to the user to call the endpoint to obtain further content, including the artist's channel_id. I am however open to ideas on how this part can be better presented to the user.
PR also adds `bottom_button` to `MusicShelf`. If you follow the endpoint of a library artist, you will see one such button with the 'See All By Artist' text.

Fix `music#library.getArtists()` and add `MusicShelf.bottom_button`

---

package-lock.json
package.json
src/Innertube.ts
src/core/AccountManager.ts
src/core/Actions.ts
src/core/InteractionManager.ts
src/parser/classes/ChannelOptions.ts
src/parser/classes/CopyLink.ts
src/parser/classes/NavigationEndpoint.ts
src/parser/classes/PageIntroduction.ts
src/parser/classes/SettingsCheckbox.ts
src/parser/classes/SettingsOptions.ts
src/parser/classes/SettingsSidebar.ts
src/parser/classes/SettingsSwitch.ts
src/parser/classes/comments/Comment.ts
src/parser/classes/comments/CommentThread.ts
src/parser/map.ts
src/parser/youtube/Comments.ts
src/parser/youtube/Settings.ts
src/proto/index.ts
src/utils/Utils.ts

As I said in the issue, the older implementation was very inefficient and hard to maintain. This implements a proper settings parser which allows the user to navigate through the page however they want to. Also adding `Innertube#call(endpoint)` to simplify endpoint calls.
```ts
const settings = await yt.account.getSettings();
// View sidebar menu items
console.info(settings.sidebar_items);
// Select an item from the sidebar menu, this throws an error if the item doesn't exist
const notifications = await settings.selectSidebarItem('Notifications');
// View setting options
console.log(notifications.setting_options);
// Get a setting option, also throws an error if the option doesn't exist
const option = notifications.getSettingOption('Recommended videos');
// And lastly, toggle it on or off …
```

feat: add settings page parser

---

src/parser/ytmusic/Artist.ts

Example `id` that throws error when calling `Music#getArtist()`: 
```
// This channel does not have MusicShelf sections
// https://music.youtube.com/channel/UC9PTPzzGQ-C_kDHlwQOrDFQ
const id = 'UC9PTPzzGQ-C_kDHlwQOrDFQ'; 
const artist = await youtube.music.getArtist(id); // throws error
```
This PR fixes this.

fix: `Music#Artist`parse err if missing shelves

---

src/parser/classes/DidYouMean.ts

This PR includes `correctedQueryEndpoint` in the data parsed by `DidYouMean`. Currently the parser takes endpoint data from `navigationEndpoint`. I have not encountered this in my search tests (ytmusic) but it could well exist somewhere so I decided not to remove it.
Also added `text`prop for sake of completeness.

Fix `DidYouMean` endpoints and add `text` prop

---

src/parser/classes/MusicVisualHeader.ts
src/parser/map.ts
src/parser/ytmusic/Artist.ts

Some artists have a `MusicVisualHeader` instead of the more common `MusicImmersiveHeader`. This PR adds the missing parser class so `Music#Artist` won't error when this type of header is encountered.
Example channel ID with `MusicVisualHeader`:  [UCsykiwtxpFJsdBHaEhWGXFw](https://music.youtube.com/channel/UCsykiwtxpFJsdBHaEhWGXFw)

feat: add `MusicVisualHeader`

---

src/core/Music.ts
src/parser/youtube/VideoInfo.ts

Include signature timestamp in the request to `/player` for YouTube Music and add a small check for microformats (youtube/VideoInfo).

fix: ytmusic formats returning 401 when deciphered

---

src/core/Music.ts

Private albums (created automatically when you upload songs to ytmusic) have IDs starting with `FEmusic_library_privately_owned_release`. This fails the ID check in `Music#getAlbum()`. This PR fixes this.

fix: `Music#getAlbum()`fails for private album ID

---

src/parser/classes/livechat/items/LiveChatPaidMessage.ts
src/parser/classes/livechat/items/LiveChatPaidSticker.ts

I added some color info to LiveChatPaidMessage and LiveChatPaidSticker.
Actual response from YouTube has some color info: red for expensive purchase and blue for cheap one, etc..., but LiveChatPaidMessage and LiveChatPaidSticker of current version don't have them.
So I added `headerBackgroundColor`, `headerTextColor`, `bodyBackgroundColor`, `bodyTextColor` to LiveChatPaidMessage and `moneyChipBackgroundColor`, `moneyChipTextColor`, `backgroundColor`, `authorNameTextColor` for LiveChatPaidSticker.
I locally ran `Parser.parseResponse` with actual responses contains `liveChatPaidMessageRenderer` and `liveChatPaidStickerRenderer`, and it seems to works well.
no related issues

feat: Add paid chat color info

---

README.md
src/core/Actions.ts
src/core/Music.ts
src/parser/index.ts
src/parser/youtube/VideoInfo.ts
src/parser/ytmusic/Recap.ts
src/parser/ytmusic/TrackInfo.ts
src/utils/Constants.ts

This adds support for the playback tracking API. I've only implemented the ability to add videos/songs to the watch history — as actually tracking the playback is a bit more complicated, since it requires the client to poll the endpoint every 30-60 seconds with information about player position among other things. 
```ts
// ...
// or const info = await yt.music.getInfo('k79dMVVmvA8');
const info = await yt.getInfo('k79dMVVmvA8');
await info.addToWatchHistory();
```

feat: add `<info>#addToWatchHistory()`

---

package-lock.json
package.json
src/parser/classes/TitleAndButtonListHeader.ts
src/parser/map.ts
src/parser/youtube/Search.ts
test/main.test.ts

This fixes search continuations & refinement cards.
Related: #172

fix: search continuations not being parsed correctly 

---

src/parser/classes/livechat/items/LiveChatAutoModMessage.ts
src/parser/map.ts

I create new livechat item: `LiveChatAutoModMessage`.
This item is only available for streamers themselves and their modelators.
Some chat items such as lil bit sensitive one will be pending, and only streamers and moderators can see the item and decide to or not to show by click buttons on the chat layer.
`LiveChatAutoModMessage` has such infos.
- `auto_moderated_item` is the pending item whose type is such as LiveChatTextMessage.
- `header_text` is the message means "This message is pending." in their local language.
- `timestamp` and `id` are same as others.
Actual Responses from YouTube has other data such as endpoint to handle messages by moderator and something, but my parser doesn't parse them.
I locally ran `Parser.parseResponse` with actual responses contains …

feat: add LiveChatAutoModMessage

---

src/parser/classes/livechat/items/LiveChatPaidMessage.ts
src/parser/classes/livechat/items/LiveChatTextMessage.ts
src/parser/classes/livechat/items/LiveChatTickerPaidMessageItem.ts

fix: `LiveChatAuthorBadge` where `MetadataBadge` was expected

---

src/parser/classes/CollaboratorInfoCardContent.ts
src/parser/map.ts

Add `CollaboratorInfoCardContent`, this renderer represents channels in the `CardCollection` list.
Related: #174

feat: add `CollaboratorInfoCardContent` renderer parser

---

src/parser/classes/LiveChatDialog.ts
src/parser/classes/SegmentedLikeDislikeButton.ts
src/parser/map.ts

Mostly minor additions —
`LiveChatDialog` usually appears when a channel has a pinned live chat comment advertising merchandise.

feat(LiveChat): add `SegmentedLikeDislikeButton` and `LiveChatDialog`

---

docs/API/music.md
src/core/Actions.ts
src/core/Music.ts
src/parser/classes/AudioOnlyPlayability.ts
src/parser/classes/BrowserMediaSession.ts
src/parser/classes/MusicDownloadStateBadge.ts
src/parser/classes/MusicItemThumbnailOverlay.ts
src/parser/classes/MusicQueue.ts
src/parser/classes/MusicResponsiveListItem.ts
src/parser/classes/MusicTwoRowItem.ts
src/parser/classes/NavigationEndpoint.ts
src/parser/classes/PlayerOverlay.ts
src/parser/index.ts
src/parser/map.ts
src/parser/ytmusic/TrackInfo.ts
test/main.test.ts

This fixes a few inconsistencies in `Innertube#music`, adds `<track_info>#getTab()`, `<track_info>#getRelated()`, `<track_info>#getUpNext()` and `<track_info>#getLyrics()`.
```ts
const info = await yt.music.getInfo('video_id');
// Get tabs available in the page 
console.info(info.available_tabs);
// Retrieve a tab and its contents
const target_tab = await info.getTab('Related');
console.log(target_tab);
// Retrieve up next with autoplay/automix on (default)
const up_next = await info.getUpNext(true); // or Music#getUpNext(id_here, true)
console.info(up_next);
// Retrieve lyrics
const lyrics = await info.getLyrics();
console.info(lyrics);
// Retrieve related content
const related = await info.getRelated();
console.info(related);
```
Fixes #182

feat(Music): add automix support and minor improvements 

---

README.md
src/Innertube.ts
src/core/Session.ts
src/parser/youtube/VideoInfo.ts
src/utils/Constants.ts
src/utils/HTTPClient.ts

This adds support for the `TVHTML5_SIMPLY_EMBEDDED_PLAYER` client, which is able to bypass some age restricted videos. See #191, thanks @unixfox!
```ts
// Video info
const info = await yt.getInfo('somevideoid', 'TV_EMBEDDED');
console.log(info);
// Download 
const stream = await yt.download('somevideoid', {
type: 'video+audio',
quality: 'best',
client: 'TV_EMBEDDED'
});
const file = createWriteStream('./video.mp4');
for await (const chunk of streamToIterable(stream)) {
file.write(chunk);
}
```

feat: add `TVHTML5_SIMPLY_EMBEDDED_PLAYER` client

---

package.json
src/core/Actions.ts
src/parser/classes/NavigationEndpoint.ts
src/parser/classes/livechat/items/LiveChatAutoModMessage.ts
src/parser/classes/livechat/items/LiveChatPaidSticker.ts
src/parser/classes/livechat/items/LiveChatTextMessage.ts
src/parser/index.ts
src/parser/youtube/ItemMenu.ts
src/parser/youtube/LiveChat.ts

I implemented moderation of live chat, which is mentioned at issue #186.
- add `LiveChat.getItemMenu(item: ChatItemHasMenuEndpoint)`
You can call this method with `ChatItemHasMenuEndpoint`: chat item which has `menu_endpoint` member such as 
`LiveChatTextMessage`, and get all endpoints for moderating the chat item whose type is `Promise<Menu>`. You can call the 
moderation endpoint in the `Menu` instanse you got by following `LiveChat.selectButtonItem()` method.
- add `LiveChat.selectButtonItem(button: Button)`
You can call chat moderation endpoint whose type is `Button` (or its sub class such as `MenuServiceItem`) with this method.
The modelation endpoint comes from the response of  `LiveChat.getItemMenu()`, `LiveChatTextMessage.inline_action_buttons` or …

Live Chat - Implement moderation

---

src/parser/classes/livechat/RemoveChatItemAction.ts
src/parser/classes/livechat/items/LiveChatTickerPaidStickerItem.ts
src/parser/map.ts

This seems to be a new action and replacement for `MarkChatItemAsDeletedAction`.
Actual response has only target_id
This is a ticker item for `LivaChatPaidSticker`.
No related issues

Live Chat - add RemoveChatItemAction and LiveChatTickerStickerItem

---

src/parser/classes/livechat/RemoveChatItemByAuthorAction.ts
src/parser/map.ts
src/parser/youtube/LiveChat.ts

Removes the use of `setTimeout`/`setInterval` for polling and instead measures polling interval according to how many actions were emitted in the previous req, if there were 0 actions then the default polling interval will be `1000ms`. This also slightly improves performance for live chats with a larger number of viewers.

refactor: improve live chat polling 

---

src/Innertube.ts

Playlist ids can contain `VL`. Example: https://www.youtube.com/playlist?list=PLakb9q7NpRvVL-j6lY85YW4GEWvrf8sXM
The current code would corrupt the playlist id by removing `VL` anywhere in the string.
This behavior is not documented and doesn't have a test.
I don't think this function should try to remove `VL`, but I can fix the regex to `/^VL/` instead if requested.

Don't remove "VL" from playlist id

---

src/parser/index.ts

Resolves #218
This commit adds a static `Parser#setParserErrorHandler` method to allow users to catch errors in the parser themselves.

feat: custom parser error handler

---

README.md
src/Innertube.ts
src/core/Feed.ts
src/core/FilterableFeed.ts
src/parser/classes/FeedFilterChipBar.ts
src/parser/classes/RichGrid.ts
src/parser/classes/RichItem.ts
src/parser/classes/RichSection.ts
src/parser/classes/RichShelf.ts
src/parser/youtube/HomeFeed.ts
test/main.test.ts

`Innertube#getHomeFeed()` now returns a `HomeFeed` object instead of a `FilterableFeed`. That should make things less confusing, improves parsing and it is easier to work with.
Usage:
```ts
const home = await yt.getHomeFeed();
console.log(home);
// Apply filters
const filtered_homefeed = await home.applyFilter('Music');
console.log(filtered_homefeed);
// Get feed continuation
const homefeed_continuation = await home.getContinuation();
console.log(homefeed_continuation);
// The HomeFeed object extends FilterableFeed, so its getters are still available:
console.log(home.videos);
console.log(home.posts);
console.log(home.filters).
// etc....
```

refactor: improve home feed parsing

---

src/core/AccountManager.ts
src/core/Actions.ts
src/core/InteractionManager.ts
src/core/PlaylistManager.ts
src/core/Session.ts
src/core/Studio.ts
src/utils/HTTPClient.ts

Adds support for switching accounts with cookie based authentication, as suggested by #229.
Usage:
```ts
//...
cache: new UniversalCache(),
account_index: 0, // In this case, 0 would be the first account
cookie: 'VISITOR_INFO1_LIVE=Cvx_zk; PREF=tx=America ...'
});
// Check if we're on the desired account:
const settings = await yt.getSettings();
console.info(settings.introduction);
```

feat: add support for switching accounts (cookie based auth only)

---

README.md
src/core/Feed.ts
src/parser/classes/SectionList.ts
src/parser/youtube/Channel.ts
test/constants.ts
test/main.test.ts

Adds support for applying filters to a channel's video/livestream/shorts list. 
```ts
const channel = await yt.getChannel('somechannelid');
const videos_tab = await channel.getVideos();
// Get filter list:
console.info(videos_tab.filters);
// Apply a filter:
const filtered_video_list = await videos.applyFilter('Popular');
console.info(filtered_video_list.videos);
```

feat(Channel): add support for filters

---

src/core/Actions.ts
src/core/Music.ts
src/core/Session.ts
src/parser/classes/misc/Format.ts
src/parser/youtube/VideoInfo.ts

This makes the `Player` instance optional when creating new sessions, as suggested by @absidue on Discord.
Usage:
```ts
import { Innertube, Session, UniversalCache } from 'youtubei.js';
(async () => {
const { context, api_key, api_version, account_index } = await Session.getSessionData();
const session = new Session(
context,
api_key,
api_version,
account_index,
undefined, // Player
undefined, // Cookies
undefined, // Fetch
new UniversalCache()
);
const yt = new Innertube(session);
// ...
})();
```

feat: make `Player` instance optional

---

src/core/Player.ts

The signature decipher code extraction was failing due to the way functions are being called in player [11667490](https://www.youtube.com/s/player/11667490/player_ias.vflset/en_US/base.js). Ex: instead of `MC.if(a, 71)`, it uses `MC["if"](a, 71)`.
Note:
If you are using UniversalCache, you will have to clear it so the library can extract the deciphers correctly.
Fixes #248

fix: signature decipher extraction failing

---

src/parser/classes/misc/TextRun.ts
test/constants.ts
test/main.test.ts

YouTube allows users to use bold, italics and strikethrough formatting in their comments (presumably also in video descriptions, I haven't found a video to test my theory though). This pull request makes the parser extract that formatting information. The main use for this, is to be able to replicate the appearance of comments on YouTube, while showing the comments to users.
A good video to test this with is https://www.youtube.com/watch?v=OqiXFXlYFi8, which is mentioned in this article about how to do the formatting https://www.simplehelp.net/2021/08/19/how-to-format-text-in-youtube-comments-bold-italicized-or-crossed-out/

feat(TextRun): add support for formatting

---

src/parser/classes/Button.ts
src/parser/classes/ExpandableMetadata.ts
src/parser/classes/HorizontalCardList.ts
src/parser/classes/MacroMarkersListItem.ts
src/parser/classes/MetadataBadge.ts
src/parser/classes/Video.ts
src/parser/map.ts
src/parser/youtube/Search.ts

For some reason we had `Video#is_live` commented out, this PR fixes that. This also adds the `ExpandableMetadata` node, which usually contains video chapters data.

feat: bring back `Video#is_live` and add `ExpandableMetadata`

---

src/core/Music.ts
src/core/TabbedFeed.ts
src/parser/classes/C4TabbedHeader.ts
src/parser/classes/ChannelAboutFullMetadata.ts
src/parser/classes/SectionList.ts
src/parser/helpers.ts
src/parser/youtube/Channel.ts
src/parser/youtube/Search.ts
src/parser/youtube/Settings.ts
src/parser/youtube/TimeWatched.ts
src/parser/ytmusic/Explore.ts
src/parser/ytmusic/HomeFeed.ts
src/parser/ytmusic/Library.ts
src/parser/ytmusic/Playlist.ts
src/parser/ytmusic/Recap.ts
src/parser/ytmusic/Search.ts
src/parser/ytmusic/TrackInfo.ts

Some parts of the parser relied on localised strings to find specific YTNodes, and due to the nature of these strings some features would end up breaking if a different language was used. This PR should fix most of those issues.

refactor: reduce reliance on localised strings

---

src/core/Session.ts
src/parser/classes/CompactVideo.ts
src/parser/classes/GridVideo.ts
src/parser/classes/PlaylistPanelVideo.ts
src/parser/classes/PlaylistVideo.ts
src/utils/HTTPClient.ts

Implements #259. 
```ts
(async () => {
lang: 'en',
location: 'HK',
cache: new UniversalCache()
});
const home = await yt.getHomeFeed();
console.log(home);
// ...
})();    
```
Or:
```ts
import { Innertube, Session, UniversalCache } from 'youtubei.js';
(async () => {
const { context, api_key, api_version, account_index } = await Session.getSessionData('en', 'HK');
const session = new Session(
context,
api_key,
api_version,
account_index,
undefined, // Player
undefined, // Cookies
undefined, // Fetch
new UniversalCache()
);
const yt = new Innertube(session);
const home = await yt.getHomeFeed();
console.log(home);
})();    
```

feat(Session): allow overriding geolocation

---

src/proto/index.ts
src/utils/Constants.ts

As of December 16, YouTube Studio (Android) endpoints fail with a ["Precondition check failed." ](https://github.com/LuanRT/ApodYT/actions/runs/3739549142/jobs/6346892168) message. If a newer version of the YouTube app is used then it throws a `404`, indicating that it is now a requirement to use the correct client for YT Studio requests. I would say that's a bit of a bummer as we'll have to keep track of yet another client's version to make sure it doesn't get _too outdated_.

fix: add YouTube Studio to the list of clients

---

README.md
examples/channel/basic-info.ts
src/parser/classes/ExpandableTab.ts
src/parser/youtube/Channel.ts
test/main.test.ts

This was already possible before (could be done by simply finding the search tab and then calling its nav endpoint), but I figured it'd make more sense to have a native implementation.
```ts
(async () => {
const yt = await InnerTube.create({ cache: new UniversalCache() });
const channel = await yt.getChannel('UCXuqSBlHAE6Xw-yeJA0Tunw');
const search = await channel.search('e-ink');
console.log(search.videos);
})();
```

feat: add support for searching within a channel

---

src/parser/classes/Chapter.ts
src/parser/classes/DecoratedPlayerBar.ts
src/parser/classes/HeatMarker.ts
src/parser/classes/Heatmap.ts
src/parser/classes/MultiMarkersPlayerBar.ts
src/parser/classes/PlayerOverlay.ts
src/parser/classes/TimedMarkerDecoration.ts
src/parser/map.ts
test/main.test.ts

Adds support for chapters & heatmap. Here are a few examples of how this can be used:
```ts
(async () => {
const yt = await Innertube.create({ cache: new UniversalCache() });
const info = await yt.getInfo('5DrSU72hOUQ');
const markers_map = info.player_overlays?.decorated_player_bar?.player_bar?.markers_map;
const chapters = (
markers_map?.get({ marker_key: 'AUTO_CHAPTERS' }) ||
markers_map?.get({ marker_key: 'DESCRIPTION_CHAPTERS' })
)?.value.chapters;
if (chapters) {
console.log('Chapters:\n');
for (const chapter of chapters) {
console.log(chapter.title.toString(), ' - Starts in ', Math.round(chapter.time_range_start_millis / 1000), 'seconds');
}
}
})();
```
Output:
```
Chapters:
Intro  - Starts in  0 seconds
Paul and Morgan  - …
```

feat: add support for chapters & video heatmap

---

README.md
src/Innertube.ts
src/parser/index.ts
test/constants.ts
test/main.test.ts

Adds support for resolving URLs with InnerTube's `/navigation/resolve_url` endpoint. 
```ts
(async () => {
const yt = await Innertube.create({ cache: new UniversalCache() });
const response = await yt.resolveURL('https://www.youtube.com/@pewdiepie');
console.log(response);
})();
```
Output:
```
NavigationEndpoint {
type: 'NavigationEndpoint',
payload: { browseId: 'UC-lHJZR3Gqxm24_Vd_AJ5Yw', params: 'EgC4AQDyBgQKAjIA' },
metadata: {
url: '/youtubei/v1/navigation/resolve_url',
page_type: 'WEB_PAGE_TYPE_CHANNEL',
api_url: 'browse'
}
}
```
Closes #116

feat: implement `Innertube#resolveURL(url)`

---

src/core/Session.ts
test/main.test.ts

Adds support for safety mode, see #266.
Unrelated: this also simplifies the creation of sessions without a player instance,
```ts
(async () => {
cache:  new UniversalCache(),
enable_safety_mode: true,
retrieve_player: true
});
// ...
})();
```

feat: allow enabling safety mode

---

src/Innertube.ts
src/proto/index.ts
src/proto/youtube.proto
src/proto/youtube.ts

See #246.
```ts
import { Innertube, UniversalCache, YTNodes } from 'youtubei.js';
(async () => {
const yt = await Innertube.create({ cache: new UniversalCache() });
const search = await yt.search('Japan', { type: 'video', features: [ '4k', 'hdr', 'creative_commons' ] });
console.log(search.videos.filterType(YTNodes.Video));
})();
```
Closes #246.

feat(Search): add support for `features` filter

---

src/parser/classes/misc/VideoDetails.ts
test/constants.ts
test/main.test.ts

The current `is_live_content` property only tells you whether the video is a normal one or a live stream, it doesn't provide enough granularity on whether the live stream is live, upcoming or a live stream replay, it's true for all three of those. Extracting the `is_live` and `is_upcoming` properties as well, solves that.
Below is a table of the values of those 3 properties for the 4 types of videos mentioned above.
| Type | `is_live` | `is_live_content` | `is_upcoming` |
| --- | --- | --- | --- |
| currently live live stream | `true` | `true` | `false` |
| live stream replay | `false` | `true` | `false` |
| upcoming live stream | `false` | `true` | `true` |
| normal video | `false` | `false` | `false` |
I haven't added any tests as it'll be hard to find continously running live streams …

feat: Add is_live and is_upcoming to VideoDetails

---

src/parser/classes/PlayerMicroformat.ts
src/parser/youtube/VideoInfo.ts
test/main.test.ts

Upcoming live streams and currently live live streams have a start time, which YouTube helpfully tells us about. Some of the use cases for having access to this are showing it to a user, notifications for when a live stream starts or other automations.

feat: Add live stream start_timestamp

---

src/parser/classes/TwoColumnWatchNextResults.ts
src/parser/helpers.ts
src/parser/youtube/VideoInfo.ts
test/main.test.ts

Fixed issues discussed in #69. The watch next feed has a slightly different layout for unauthenticated sessions.
Closes #69.

fix(VideoInfo): watch next feed not being parsed when logged out

---

src/core/Session.ts
src/proto/index.ts
src/proto/youtube.proto
src/proto/youtube.ts
src/utils/Constants.ts
test/main.test.ts

As the title says, this allows sessions to be created without having to make a call to YouTube's service worker endpoint.
```ts
(async () => {
cache:  new UniversalCache(),
generate_session_locally: true
});
// ...
})();
```
This also improves code documentation.

feat: add support for generating sessions locally

---

src/parser/youtube/LiveChat.ts

The LiveChat object will be used by users of this library for a much longer amount of time than the VideoInfo, as it needs to stick around for the events to be emitted. By storing the video and channel IDs directly inside the LiveChat object instead of storing the whole (large) VideoInfo object, we allow the JavaScript VM to garbage collect the VideoInfo object (and the many objects inside of it) when there are no more references to it in the library user's code, lowering the memory usage.
In FreeTube for example we read the info that we want from the VideoInfo object, then get the live chat if there is one, after that the FreeTube code no longer references the VideoInfo object. With this change, YouTube.js won't hold any references to it either, so it can get garbage collected.

refactor(LiveChat): Only store required video info values

---

src/parser/classes/misc/EmojiRun.ts

With normal emojis the `emoji_id` is the actual emoji, so when you display the image it works well as the alt text. The `emoji_id` for custom emojis however is the id of it on YouTube's servers, so a bunch of letters with a slash in the middle, which doesn't work well as an alt text, in those cases using the shortcuts and search terms as the alt text would be more user friendly. To make it easier to handle emojis and custom emojis differently (my first thought was to use this regex `/(\p{Emoji_Presentation}|\p{Extended_Pictographic})/u` in the FreeTube code, until i had the thought that YouTube might already do it for us), this PR extracts YouTube's `isCustomEmoji` property.

feat(EmojiRun): Add is_custom to identify custom emojis

---

src/parser/youtube/Playlist.ts

I saw this issue in https://github.com/FreeTubeApp/FreeTube/issues/3046 and figured I'd take a crack at it. It would seem that InnerTube has some trouble loading the last videos of long playlists (perhaps because they can only load in batches of 100 videos and never less than that?).
Since the library never expects `on_load_received_actions` to be undefined when doing pagination, it thinks the response is not parsed and tries to parse it, inevitably ending up in a `InnertubeError: Type not found!` which is then followed by `InnertubeError: This playlist does not exist` when retrieving the last page of a long playlist. It says “Type not found” because it's trying to run `Parser#parseResponse` on the parsed data all over again. To fix this, I explicitly set `already_parsed` to `true` in …

fix(Playlist): trying to parse an already parsed response

---

src/parser/youtube/VideoInfo.ts

Occasionally YouTube doesn't return a continuation in the watch next feed, which causes this error: `Cannot cast CompactVideo to one of ContinuationItem`.

fix(VideoInfo): Gracefully handle missing watch next continuation

---

README.md
docs/API/account.md
docs/API/kids.md
docs/API/music.md
src/Innertube.ts
src/core/Kids.ts
src/core/Session.ts
src/parser/classes/CompactChannel.ts
src/parser/classes/SlimOwner.ts
src/parser/classes/SlimVideoMetadata.ts
src/parser/classes/ytkids/AnchoredSection.ts
src/parser/classes/ytkids/KidsCategoriesHeader.ts
src/parser/classes/ytkids/KidsCategoryTab.ts
src/parser/classes/ytkids/KidsHomeScreen.ts
src/parser/map.ts
src/parser/youtube/VideoInfo.ts
src/parser/ytkids/HomeFeed.ts
src/parser/ytkids/Search.ts
src/parser/ytkids/VideoInfo.ts
src/parser/ytmusic/TrackInfo.ts
src/utils/Constants.ts
src/utils/FormatUtils.ts
src/utils/HTTPClient.ts
test/constants.ts
test/main.test.ts

Adds support for YouTube Kids. See #284 for more info.
```ts
(async () => {
// Search:
const search = await yt.kids.search('cocomelon');
console.log(search);
// Home feed:
const home = await yt.kids.getHomeFeed();
console.log(home);
// Get available categories:
console.log(home.categories);
// Select a feed category:
const music_ctg = await home.selectCategoryTab('Music');
console.log(music_ctg.videos);
// Get video info:
const info = await yt.kids.getInfo('ApXoWvfEYVU');
console.log(info);
})();
```
Closes #284

feat: add support for YouTube Kids

---

README.md
docs/API/kids.md
docs/API/music.md
src/parser/classes/PlayerCaptionsTracklist.ts
src/parser/classes/misc/Format.ts
src/parser/youtube/VideoInfo.ts
src/parser/ytkids/VideoInfo.ts
src/parser/ytmusic/TrackInfo.ts
src/utils/FormatUtils.ts

The goal of this PR is to make it easier to identify and extract the audio tracks of videos with multilingual audio. ~~I'm also considering adding an option to filter out unwanted formats from the DASH manifest and download function, which is why this is a WIP.~~ (done)
```ts
import { Innertube, UniversalCache, YTNodes } from 'youtubei.js';
(async () => {
const search = await yt.search('mrbeast I Survived 50 Hours In Antarctica', { type: 'video' });
const video_id = search.results?.firstOfType(YTNodes.Video)?.id as string;
const info = await yt.getInfo(video_id);
// Remove unwanted formats from the DASH manifest:
console.log(info.toDash(undefined, (fmt) => {
// Remove all non-English audio …
```

feat: improve support for dubbed content

---

README.md
src/parser/classes/ChannelSubMenu.ts
src/parser/classes/SectionList.ts
src/parser/classes/SortFilterSubMenu.ts
src/parser/map.ts
src/parser/youtube/Channel.ts

Adds support for sorting the playlist tab, see #290 for more details.
```ts
(async () => {
const channel = await yt.getChannel('UCez-2shYlHQY3LfILBuDYqQ');
let playlists_tab = await channel.getPlaylists();
/**
* Channels such as UCez-2shYlHQY3LfILBuDYqQ have their playlists organized into various categories. 
* In this case, sorting is only possible after a category is selected.
*/
if (!playlists_tab.memo.has('SortFilterSubMenu')) {
console.info('Content type filters:', playlists_tab.content_type_filters);
playlists_tab = await playlists_tab.applyContentTypeFilter('Created playlists');
}
console.info('Sort filters:', …
```

feat(Channel): add support for sorting the playlist tab

---

src/parser/classes/CompactVideo.ts

This looks for a badge to determine if a CompactVideo is live

Feat: parse isLive in CompactVideo

---

src/core/TabbedFeed.ts
src/parser/youtube/Channel.ts
test/constants.ts
test/main.test.ts

Certain YouTube channels don't have all tabs, depending on what type of content they post. When you are displaying the channel in a GUI, you may want to hide the missing tabs, like YouTube itself does. Currently the only to do that with YouTube.js is to try calling `await channel.getShorts()` and check the error message, unfortunately that also means that if the tab does exist, you will have fetched the content of that tab before the user has even switched to it.
This pull request adds getters to check if the Videos, Shorts, Live Streams and Community tabs exist, without making any requests. Those 4 tabs are the only ones I've notice missing in various combinations depending on the channel. I can add getters for the other tabs just in case, if you would like me to?

Allow checking whether a channel has optional tabs

---

src/parser/classes/PostMultiImage.ts
src/parser/map.ts

MultiImage community posts were not parsed
related: 
https://github.com/FreeTubeApp/FreeTube/pull/1568
Useful channel id for testing community post types: UCnkp4xDOwqqJD7sSM3xdUiQ

Add parser support for MultiImage community posts

---

src/parser/classes/ChannelAboutFullMetadata.ts

Some channels don't have any primary links, think the channels that get generated for every user account but most YouTube users probably don't even know that they have a channel associated with their account.
Currently it prints a warning because it's calling `.map` on `undefined` in those situations.

fix(ChannelAboutFullMetadata) Fix error when there are no primary links

---

src/parser/classes/TopicChannelDetails.ts

This pull request fixes the title and subtitle properties on the TopicChannelDetails being identical and the avatar array being empty.
I haven't come across a case where `data.thumbnail` actually existed but I've left it in there just in case there is an edge case that uses it.

fix(TopicChannelDetails): avatar and subtitle parsing

---

src/parser/youtube/Channel.ts
test/constants.ts
test/main.test.ts

Follow up to #296
Since making that pull request, I've noticed that there are auto generated channels that don't have any tabs like https://www.youtube.com/@gaming (technically it does have a single tab but it's unlabeled and doesn't have a navigation endpoint) so I've added getters for the remaining tabs. Additionally it doesn't have a search field, so I added a getter for that too.

feat(Channel): Add getters for all optional tabs

---

src/utils/FormatUtils.ts

Currently the DASH manifest doesn't include any language or default track information, which is fine for videos that only have a single audio track/language, as the player will just pick the first audio format that it can play, however for videos with multiple different audio track in different languages, that means that the player still picks the first one it can play, which is likely to be in a different language than the original video audio. For Mr. Beast videos that means listening to the video in Arabic, with no way to change it.
If the video has multiple languages, this pull request adds the language and default track information to the DASH manifest. I also added the audioSamplingRate, as the DASH specification says that it should be included in the manifest, that will now be …

feat(FormatUtils): Support multiple audio tracks in the DASH manifest

---

src/parser/classes/CompactVideo.ts
src/parser/classes/MetadataBadge.ts
src/parser/classes/Video.ts

For MetaDataBadge: Assign `label` to label property instead of assigning `label` to style property  (introduced in #256 )

Fix: Assign MetaDataBadge's label

---

README.md
src/Innertube.ts
src/parser/classes/HashtagHeader.ts
src/parser/map.ts
src/parser/youtube/HashtagFeed.ts
src/proto/generated/messages/youtube/(Hashtag)/Params.ts
src/proto/generated/messages/youtube/(Hashtag)/index.ts
src/proto/generated/messages/youtube/Hashtag.ts
src/proto/generated/messages/youtube/index.ts
src/proto/index.ts
src/proto/youtube.proto
test/main.test.ts

Adds support for retrieving hashtag pages. Closes #301.
```js
cache: new UniversalCache(false),
generate_session_locally: true
});
const hashtag = await yt.getHashtag('macmiller');
console.log('#macmiller:', hashtag);
// Apply a filter to the hashtag feed:
const shorts = hashtag.applyFilter('Shorts');
console.log('Shorts:', shorts);
```

feat: add support for hashtag feeds

---

README.md

Adds Deno import closing #314, and fixes the web imports.

docs: update imports for platforms

---

src/parser/classes/PlaylistVideo.ts
src/parser/classes/ThumbnailOverlayTimeStatus.ts

Currently the live and upcoming status as well as the premiere date of playlist videos is not extracted. I choose property names that are the same as the ones in `src/parser/classes/Video.ts`.
Here are two playlists I found that can be used to test it (went to youtube.com/live, clicked through to the channels and looked for playlists with the live and upcoming videos in them):
Live: https://www.youtube.com/playlist?list=PL6NdkXsPL07IFb3kA-m9QNY8oUMctNM3i
Upcoming: https://www.youtube.com/playlist?list=PLT2PUxNJBoeONIclW0JlAhuX8j7umZKwZ

feat: Add upcoming and live info to playlist videos

---

src/parser/classes/PlayerMicroformat.ts

Videos like https://www.youtube.com/watch?v=HQMkxmtPZhg don't have the embed property in the player microformat response, which causes YouTube.js to log an error about not being able to access `iframeUrl` on undefined.

fix(PlayerMicroformat): Make the embed field optional

---

src/parser/classes/NavigationEndpoint.ts
src/parser/classes/VideoSecondaryInfo.ts
src/parser/classes/misc/TextRun.ts

Adds support for YouTube's new attributed descriptions and its attachment runs.
The library should now be able to provide the data correctly as well as generate valid html with for the description. Here's an example of a description rendered by YouTube.js:
Old description type:
Attributed description:
As seen above, this new description type treats YouTube specific links differently instead of rendering them like other links.
Closes #319

feat(VideoSecondaryInfo): add support for attributed descriptions

---

src/core/Feed.ts
src/parser/classes/SharedPost.ts
src/parser/map.ts

Add support for SharedPost in community tab.
Fixes #331

feat(parser): SharedPost

---

src/parser/classes/RichMetadata.ts
src/parser/classes/RichMetadataRow.ts
src/parser/map.ts
src/parser/youtube/VideoInfo.ts

Adds game info support to `getInfo()` and the in my opinion missing basic info `category` to `getBasicInfo()`.
```
const yt = await Innertube.create({ cache: new UniversalCache(false), generate_session_locally: true });
const info = await yt.getInfo('bhpwmmr_aEQ');
console.log(info?.game_info?.title.toString(), info?.game_info?.release_year.toString());
```
**Output:**
> Yu-Gi-Oh! Master Duel 2022
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] My changes generate no new warnings
- [ x ] I have checked my code and corrected any misspellings

Add `game_info` to `getInfo()` and `category` to `getBasicInfo()`

---

README.md
src/Innertube.ts
src/parser/classes/GuideCollapsibleEntry.ts
src/parser/classes/GuideCollapsibleSectionEntry.ts
src/parser/classes/GuideDownloadsEntry.ts
src/parser/classes/GuideEntry.ts
src/parser/classes/GuideSection.ts
src/parser/classes/GuideSubscriptionsSection.ts
src/parser/map.ts
src/parser/parser.ts
src/parser/types/ParsedResponse.ts
src/parser/types/RawResponse.ts
src/parser/youtube/Guide.ts

Add support for fetching YouTube's content guide, contents of which you will find in the left sidebar of YT website:
```
const guide = await youtube.getGuide();
// guide.contents:
[
{
"type": "GuideSection",
"items": [
{
"type": "GuideEntry",
"title": {
"text": "Home"
},
"endpoint": {
"type": "NavigationEndpoint",
"payload": {
"browseId": "FEwhat_to_watch"
},
"metadata": {
"url": "/",
"page_type": "WEB_PAGE_TYPE_BROWSE",
"api_url": "browse"
}
},
"icon_type": "WHAT_TO_WATCH",
"is_primary": true
}
...
]
}
...
]
```

feat(yt): add `getGuide()`

---

src/parser/classes/HeroPlaylistThumbnail.ts
src/parser/classes/PlaylistHeader.ts
src/parser/map.ts

Add `banner` to `PlaylistHeader`, in case someone needs it (e.g. me). Doesn't really do much since `getPlaylist()` already fetches thumbnails and endpoint from other places in the response data, so understandable if you don't merge this :smile:

feat(parser): add `banner` to `PlaylistHeader`

---

src/parser/classes/SearchFilter.ts
src/parser/classes/SearchFilterGroup.ts
src/parser/classes/SearchSubMenu.ts
src/parser/map.ts
src/parser/parser.ts
src/parser/youtube/Search.ts

Implements the `SearchSubMenu` node (and its child nodes too), which contains some useful data about the search filters.

feat(YouTube/Search): add `SearchSubMenu` node

---

src/parser/classes/PlayerLegacyDesktopYpcOffer.ts
src/parser/classes/VideoPrimaryInfo.ts
src/parser/map.ts

Adds the `PlayerLegacyDesktopYpcOffer` error screen node, which appears when trying to retrieve members-only content. This also fixes a couple of warnings regarding the `VideoPrimaryInfo` node that only appear when viewing such content as well.

fix(youtube):  add `PlayerLegacyDesktopYpcOffer` node

---

src/parser/classes/misc/Format.ts
src/utils/FormatUtils.ts

Turns out that YouTube also supports descriptive audio tracks not just dubs (courtesy of https://github.com/TeamNewPipe/NewPipeExtractor/pull/1026)
This pull request adds a new field to the Format class `is_descriptive` and also refactors the DASH manifest code to support descriptive audio tracks. Previously in #308 I did the grouping based on the language, now that we know that it's not the only differentiating factor between audio tracks, I decided to group them based on the audio track id that YouTube provides. That also makes it easier to add support for additonal audio track types in the future, if we find out there are more.
Example video: https://www.youtube.com/watch?v=TjxC-evzxdk

feat: Add support for descriptive audio tracks

---

README.md
src/Innertube.ts
src/parser/classes/TwoColumnWatchNextResults.ts
src/parser/youtube/VideoInfo.ts

Adds support for getting video info by endpoint in `getInfo()`.  In addition, add `playlist` and `autoplay` to `VideoInfo`. 
The result is that you can now obtain video info within the context of a list such as `Playlist` or `Mix`.  To illustrate, consider the following endpoint for a `Mix` item:
```
// mixEndpoint:
{
"type": "NavigationEndpoint",
"payload": {
"videoId": "XHedu3KcPP0",
"playlistId": "RDXHedu3KcPP0",
"params": "OALAAQE%3D",
"continuePlayback": true
},
...
}
// Call `getInfo()` with mixEndpoint:
const info = await youtube.getInfo(mixEndpoint);
// Now you can get not only info about the video (as referenced by id 'XHedu3KcPP0') itself, but 
// also other items in the list.
// info.playlist:
{
"id": "RDXHedu3KcPP0",
"title": "Mix - ...",
"author": ...,
"contents": [
{
"type": …
```

feat(VideoInfo): support get by endpoint + more info

---

src/parser/classes/SearchFilter.ts

1. Add `status` to `SearchFilter`; add `disabled` and `selected` getters for convenience.
2. Parse `data.navigationEndpoint` if `data.endpoint` is missing. In fact, I have never encountered `data.endpoint` for `SearchFilter` but would be cautious about removing it in case it actually exists in some cases.

Add `status` to `SearchFilter` and fix `endpoint`

---

src/parser/classes/Playlist.ts

Minor addition.
Example of `Playlist` having `view_playlist` can be found in YT search results.

feat(parser): add `view_playlist` to `Playlist`

---

README.md
src/parser/classes/GridMovie.ts
src/parser/classes/HorizontalMovieList.ts
src/parser/classes/PlayerLegacyDesktopYpcTrailer.ts
src/parser/classes/YpcTrailer.ts
src/parser/map.ts
src/parser/youtube/VideoInfo.ts

1. Add `GridMovie` and `HorizontalMovieList` parsers for movie-related elements (easy to find them in Explore -> Films)
2. Add `PlayerLegacyDesktopYpcTrailer` and `YpcTrailer` parsers for trailer info that appear in `errorScreen` of `/player` reponse, typically when viewing a non-purchased movie or film.
3. Add `getTrailerInfo()` and `has_trailer` getter to `VideoInfo`, which uses data from the parsers in (2) above. Usage:
```
const info = youtube.getInfo(video_id);
if (info.has_trailer) {
const trailer_info = info.getTrailerInfo();  // Returns `VideoInfo` instance
const format = trailer_info.chooseFormat(...);
...
}
```

feat(yt): add support for movie items and trailers

---

README.md
src/parser/classes/misc/Format.ts
src/parser/youtube/VideoInfo.ts
src/parser/ytkids/VideoInfo.ts
src/parser/ytmusic/TrackInfo.ts
src/utils/FormatUtils.ts

Some videos have formats that are a bit different than other ones, YouTube seems to refer to these as OTF. According to NewPipeExtractor (https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/DeliveryType.java#L23-L38) these can occur on videos with low view counts and live stream replays that have just been reencoded to normal videos. Instead of allowing you to request arbitrary chunks with the `range` query parameter, instead you use the `sq` query parameter to request sequences, the first sequence (`&sq=0`) contains the duration of the sequences, so we need to request it while building the DASH manifest.
This implementation was inspired by the NewPipeExtractor implementation, so big thanks to them :).
Here is a …

feat!: Add support for OTF format streams

---

src/platform/deno.ts
src/platform/node.ts
src/platform/polyfills/node-custom-event.ts
src/platform/web.ts
src/types/PlatformShim.ts
src/utils/EventEmitterLike.ts

As CustomEvent is available in Chrome, Firefox and Deno for all versions the YouTube.js supports, we don't need the CustomEvent polyfill in the web or Deno builds. CustomEvent was only added to Node.js in version 19 and as YouTube.js supports Node 10 and up, we definitely need the CustomEvent polyfill for the node build.
https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent#browser_compatibility
I decided to move it to the Platform.shim, so that it's together with all other polyfills and also only gets included for the Node.js build. This also has the advantage that it no longer affects the global scope.

refactor(shim): Move node CustomEvent polyfill to Platform.shim

---

src/utils/Utils.ts

Channels like Lofi Girl have 24/7 live streams, so when they end, the timestamps are massive https://www.youtube.com/@LofiGirl/streams, so long that they have a thousands separator for the hours. Currently the timestamp parsing can't handle the thousands separator. For this timestamp `20,843:43:51`, instead of seeing it as having `20843` hours it instead only takes the digits before the separator, so `20` hours, the result being that the seconds duration on Video objects is a lot smaller than it should be.
This pull request removes any non digit characters before parsing the strings into numbers.

fix(Utils): Properly parse timestamps with thousands separators

---

src/utils/FormatUtils.ts

It looks like video.js changed something on their end since I added support for multiple audio tracks to the DASH manifest, now it seems to require unique ids for all representations, otherwise it just silently fails to switch audio tracks :(.
This was tested in FreeTube with video.js, hopefully this doesn't break shaka (I couldn't find anything in the spec that mandated that the ids consist of only digits, so I'm not expecting anything to break).
Here is a video that can be used as a test, it contains 3 English audio tracks, the main one, one with the interviewee dubbed and a third one with audio descriptions: https://youtu.be/Kn56bMZ9OE8

fix(toDash): Generate unique Representation ids

---

src/parser/classes/Video.ts

Videos on channel pages show their live status in the thumbnail overlay instead of in a badge, this pull request adds support for that while allow it to still work correctly with search results.
https://www.youtube.com/@LofiGirl/streams

fix(parser): Fix Video.is_live on channel pages

---

src/utils/HTTPClient.ts

Fixes https://github.com/LuanRT/YouTube.js/issues/369#issuecomment-1480327454

fix(http): android tv http client missing `clientName`

---

README.md
src/core/Session.ts
src/proto/index.ts
src/utils/Utils.ts
test/main.test.ts

Adds a new option to allow custom visitor data tokens. Note that it must be a valid token.
```ts
(async () => {
const yt = await Innertube.create({ 
cache: new UniversalCache(),
generate_session_locally: true, 
visitor_data: '...'
});
})();
```

feat(Session): allow setting a custom visitor data token

---

src/parser/youtube/Search.ts

Currently YouTube.js always counts the first item section in the search response as the results, sometimes however the first item section contains ads, which means that YouTube.js doesn't return any search results. This pull request tries to find the first item section that has items.
Searching for "Marques Brownlee" with the type filter set to all, videos or channels, should make this bug show up (usually it appears for at least one of the three cases).

fix(Search): Return search results even if there are ads

---

src/parser/classes/PlaylistVideo.ts

Unfortunately playlist videos don't have fields for the uploaded date or number of views. Instead they are in the video info property. The video info property contains text runs that can consist of the short view count and uploaded date, the number of people watching the live stream or be empty.
This pull request also extracts the accessibility label string, which among other things contains the exact number of video views (thanks @AudricV for pointing that out). One important thing to note, is that said string is language dependant, so any library user wanting to parse it will have to keep that in mind, also 0 views are shown as `no views`.
Here are a couple of playlists to see the different values of those properties:
Normal videos: …

feat(PlaylistVideo): Extract video_info and accessibility_label texts

---

package-lock.json
package.json
tsconfig.json

Currently the typscript compiler adds the necessary polyfills/helpers to each file individually, this results in a lot of duplicated code. By enabling the `importHelpers` option in the tsconfig, it will instead add imports for the helpers to the files. The savings are quite large, so it definitely seems worth it.
Here are the before and after results of the bundles:
Here are the before and after results for FreeTube which uses the `youtubei.js/web` export, so the modules in the dist directory, instead of one of the bundles:

feat: Enable importHelpers in tsconfig to reduce output size

---

src/parser/classes/GuideCollapsibleEntry.ts
src/parser/classes/GuideCollapsibleSectionEntry.ts
src/parser/classes/GuideDownloadsEntry.ts
src/parser/classes/GuideEntry.ts
src/parser/classes/GuideSection.ts
src/parser/classes/GuideSubscriptionsSection.ts

This fixes a few inconsistencies in the `/guide` endpoint nodes (such as parsing props manually instead of leaving that for the parser).

refactor: fix inconsistencies in the guide endpoint nodes

---

src/parser/classes/MusicResponsiveListItem.ts
src/utils/Utils.ts

This PR makes the flex/fixed column props in the `MusicResponsiveListItem` node public, thus allowing users to parse the data as they wish. 
```ts
(async () => {
const yt = await Innertube.create({ cache: new UniversalCache(false), generate_session_locally: true });
const search = await yt.music.search('Mac Miller - Right', { type: 'song' });
console.log('Flex columns:', search.contents.first().contents.first().flex_columns);
console.log('Fixed columns:', search.contents.first().contents.first().fixed_columns);
})();
```
Closes #381

feat(MusicResponsiveListItem): make flex/fixed cols public

---

src/core/endpoints/PlayerEndpoint.ts
src/types/Endpoints.ts

Related: https://github.com/iv-org/invidious/issues/3771, https://github.com/unixfox/invidious-custom/issues/60, https://github.com/microg/GmsCore/issues/1870, https://github.com/TeamNewPipe/NewPipe/issues/9038

fix(android): workaround streaming URLs returning 403

---

src/core/Session.ts
src/core/endpoints/PlayerEndpoint.ts

YouTube now throttles clients (`WEB` only) that use shared visitor data tokens. This PR makes visitor ids (required to build a valid token) random again.
Thank you @itsmenewbie03 for reporting this issue.

fix(web): slow downloads due to visitor data

---

src/parser/youtube/VideoInfo.ts

Looks like YouTube removed the view count from the video details, as I'm not sure if it's just on my machine or for everyone, it still tries to use the view count from the video details first before falling back to the microformat one. I wonder if this didn't show up earlier because we were using a hardcoded visitor ID?

fix(VideoInfo): Use microformat view_count when videoDetails view_count is NaN

---

src/Innertube.ts
src/core/OAuth.ts
src/core/Player.ts
src/core/Session.ts
src/core/clients/Studio.ts
src/core/mixins/MediaInfo.ts
src/parser/classes/misc/Author.ts
src/parser/ytmusic/TrackInfo.ts
src/utils/Constants.ts
src/utils/FormatUtils.ts
src/utils/HTTPClient.ts

As we already use a namespace export to export the constants outside the library, we can use namespace imports to import them internally too, which improves the bundle sizes a bit, without a breaking change.
| Bundle | Before | After |
| --- | --- | --- |
| `node.cjs` | `678.3kb` | `677.2kb` |
| `browser.js` | `893.3kb` | `892.2kb` |
| `browser.min.js` | `479.6kb` | `479.2kb` |

refactor(constants): Use namespace import internally

---

src/utils/Utils.ts

As we can't rely on the `Text` class still being called Text at runtime (e.g. in FreeTube as webpack mangles names to reduce the bundle size), we should use `instanceof` instead of checking the name of the class, which will work even if the class was renamed.

fix(Utils): Use instanceof in deepCompare instead of the constructor name

---

package.json

tslib is weird. The esbuild version that YouTube.js uses, isn't able to automatically pick the correct tslib build to bundle into the browser bundles, so it uses the commonjs one, which isn't treeshakable. This makes it pick the correct one, reducing the size of the bundles:
| Bundle | Before | After |
| --- | --- | --- |
| `browser.js` | `893.3kb` | `875.8kb` |
| `browser.min.js` | `479.6kb` | `471.7kb` |
More recent versions of esbuild added support for tslib's weirdness, however they now aggressively preserve comments while bundling (previously they only preserved webpack's magic comments), so that tools like vite can add magic comments without esbuild stripping them. Unfortunately that means that it blows up the sizes of the `node.cjs` and `browser.js` bundles, because newer esbuild …

fix(bundles): Use ESM tslib build for the browser bundles

---

src/parser/classes/ReelItem.ts

ReelItems unfortunately only have their duration in one place, the accessibility label in textual form. As parsing that information out is language dependent, it should be left up to library users to do.
An example for how to parse that can be found here: https://github.com/FreeTubeApp/FreeTube/blob/bd6fb416a8b6ba388321dcc20c3d7d89c744f0f1/src/renderer/helpers/api/local.js#L300
Some examples for the accessibility label in English taken from the shorts tab on the LTT channel:
- `These mice keep getting WEIRDER... - 59 seconds - play video`
- `How Low Can Our Resolution Go? - 1 minute - play video`
- `I just found out about Elon. #SHORTS - 1 minute, 1 second - play video` (I suspect this is a rounding error on YouTube's side, as the docs say shorts can only be up to 60 seconds long, …

feat(ReelItem): Add accessibility label

---

src/utils/FormatUtils.ts

This pull request adds the audio track labels provided by YouTube to the DASH manifest. It supports both the standard Label element as well as the non-standard label attribute that shaka uses (https://github.com/shaka-project/shaka-player/issues/5019).

feat(toDash): Add audio track labels to the manifest when available

---

src/utils/FormatUtils.ts

As we only need the adaptive formats for the DASH manifest, we can skip filtering for the combined/non-DASH ones and recreating the streaming data object.

perf(toDash): Speed up format filtering

---

src/parser/youtube/Search.ts

As we only need the first match, we can do the type check inside the `find` callback. Doing it like this skips iterating over the entire array with `filterType` and then again partially with `find`, as well as the creation of the array that `filterType` (wraps `Array.filter`) returns. Now it only has to iterate over the once and only until it finds a match.

perf(Search): Speed up result parsing

---

src/parser/parser.ts

As `Object#entries` already returns an array, we don't need to wrap it in a call to `Array#from`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

chore(parser): Remove extra Array.from call

---

src/parser/classes/misc/VideoDetails.ts

Just after a live stream has finished, before YouTube has processed it into a normal video, it's a post-live DVR. The reason this property is useful is that those videos have to be treated differently than an normal one, as they just have the live stream segments. So yes they need a special manifest too but after spending ages trying to get it working with video.js, I found out that video.js doesn't support self-initializing DASH segments (segments where the initialization data is in the segment, instead of in a chunk right at the start), so we'll just be using YouTube's HLS manifest for them in FreeTube.

feat(VideoDetails): Add is_post_live_dvr property

---

src/core/endpoints/PlayerEndpoint.ts

YouTube is removing stories, so the current player params will full stop working very soon.
This pull request switches to the ones that yt-dlp is using: https://github.com/yt-dlp/yt-dlp/commit/81ca451480051d7ce1a31c017e005358345a9149

fix(PlayerEndpoint): Use different player params

---

src/core/OAuth.ts
src/utils/Constants.ts

YouTube seems to have changed their Auth script which breaks  `OAuth#getClientIdentity()`. The Client Identity regex used to match against the body of the script is bound to fail. The result is blocking of the entire process while the regex tries futilely to find a match.
This PR fixes the Client Identity matching part. From what I see, the request payload for device code also seems to have changed. Instead of `model_name`, it's now `device_model`:
So I have included this change in the PR too.

fix(OAuth): client identity matching

---

src/parser/classes/Playlist.ts

PR add `thumbnail_renderer` to the Playlist YTNode. It is given in most response, but not all, so it is an optional prop.
- Add a new property to the Playlist YTNode called `thumbnail_renderer` of type `PlaylistVideoThumbnail | undefined`
Fixes: #423 
I tested the code by linking the library to Freetube and logging out the playlist object. The thumbnail_renderer is there when it is given in the response.

fix(Playlist): Add thumbnail_renderer on Playlist when response includes it

---

src/parser/classes/misc/Format.ts
src/utils/FormatUtils.ts

This pull request adds the color information to the DASH manifest when available, this informs the player about things like HDR streams, shaka for example uses this to add `HDR` to the labels for HDR streams.
https://github.com/shaka-project/shaka-player/commit/3f9eadeaaf5d3a4b4e20c6e05dbad3fc4b4b5f3c

feat(toDash): Add color information

---

README.md
src/parser/classes/Playlist.ts
src/parser/youtube/Channel.ts

Fixes #410
This PR adds the channel methods `getReleases` and `getPodcasts`
It also fixes an issue with parsing some playlist thumbnails

Add `getReleases` and `getPodcasts` to `Channel`

---

src/parser/classes/Quiz.ts
src/parser/nodes.ts

https://github.com/FreeTubeApp/FreeTube/issues/3746
This PR allows YouTube.js to parse Quiz attachments for community posts
related: https://github.com/iv-org/invidious/pull/3978

feat(parser): Add `Quiz`

---

package-lock.json
package.json
src/utils/FormatUtils.ts

Version 1.0.0 has an export order which crashes some webpack environments (at least I came across it when using next.js 13). Updating to jinter@1.1.0 fixes it.
Fixes #432

fix(package): Bump Jinter to fix bad export order

---

src/parser/classes/comments/CommentsEntryPointHeader.ts
src/parser/classes/comments/CommentsSimplebox.ts
src/parser/nodes.ts

feat(parser): Add `CommentsSimplebox` parser

---

src/parser/classes/EngagementPanelSectionList.ts
src/parser/classes/MacroMarkersInfoItem.ts
src/parser/classes/MacroMarkersList.ts
src/parser/nodes.ts

This should fix a few parsing issues that were happening after recent updates.

feat(parser): add `MacroMarkersList`

---

src/parser/classes/PlayerCaptionsTracklist.ts
src/parser/youtube/VideoInfo.ts
src/utils/FormatUtils.ts
test/main.test.ts

For single audio track videos we currently don't have any language information, this pull request changes that to extract it from the audio track to caption mappsing that YouTube provides, when a video has captions. Additionally for videos with multiple audio tracks, this propagates the language of the default audio track to the non-DASH formats.
The goal of this pull request is to have the audio language available in a lot more situations, for videos with a single audio track without captions, it will still be unavailable unfortunately.

feat(Format): Populate audio language from captions when available

---

src/parser/classes/PlaylistHeader.ts
src/parser/youtube/Playlist.ts

With the addition of the releases channel tab, it is now a lot easier to stumble across auto-generated album playlists. Unlike normal playlists, these album ones don't seem to be tied to a specific channel. Instead of having channel information (thumbnail, name, link id, etc), they have a subtitle in this format: `{artist/artists separated by commas} • Album`.
This pull request adds support for these playlists, so that YouTube.js no longer provides an empty Author object.
Example playlists:
One artist: https://www.youtube.com/playlist?list=OLAK5uy_lM3m05hKVY9vbzZH5lJpVKZKUQ-v_iTz4
Two artists: https://www.youtube.com/playlist?list=OLAK5uy_mYnfMbIG74obySLdWtKKGj_MJ-YZqVTu0

feat(YouTube Playlist): Add subtitle and fix author optionality

---

src/parser/youtube/Playlist.ts

Playlist continuations don't have the header so we should only try extracting the subtitle for the first playlist page.
closes #464
bug introduced in #458, which added support for the subtitle

fix(Playlist): Only try extracting the subtitle for the first page

---

src/core/clients/Music.ts
src/parser/classes/MusicResponsiveListItem.ts
src/parser/youtube/Channel.ts
src/parser/ytmusic/HomeFeed.ts
src/parser/ytmusic/Library.ts
src/parser/ytmusic/TrackInfo.ts

We can't get rid of `YTNode#key` and `Maybe` completely (would be cool as the keep names esbuild setting, adds a bunch of bloat to the provided bundles and prevents function inlining), as it's needed if you use the runtime node generator with typescript projects, but we can definitely reduce where it is used. Additionally direct property accesses are slightly faster anyway and we have the type safety thanks to typescript.
I didn't make the changes in a couple of places:
- `PlaylistManager`, requires being logged in to check the types
- `Library.sections`, requires logging in to check what type `Shelf.content` is there
- `LiveChat.getItemMenu`, would require changing the exported `ChatItemWithMenu` type, which contains the `LiveChatViewerEngagementMessage` which doesn't have a …

perf: Cleanup some unnecessary uses of `YTNode#key` and `Maybe`

---

src/Innertube.ts
src/utils/Constants.ts
src/utils/HTTPClient.ts

Leveraging [f4e0f30](https://github.com/LuanRT/YouTube.js/commit/f4e0f30e6e94b347b28d67d9a86284ea2d23ee15) as my true north, this PR adds support for HLS streaming with an iOS user agent. The user agent is 100% reliable. I've been using it in my Mac/iPad/iPhone client for a number of months now and it always generates the `hls_manifest_url`.

feat(VideoInfo): support iOS client

---

src/utils/FormatUtils.ts

This pull request should fix the long standing issue with dash.js' `getBitrateInfoListFor` not working correctly, that was reported on the discord server a while back. It also addresses the more recent issue with some videos that have multiple audio tracks, also having a broken one.
https://github.com/FreeTubeApp/FreeTube/issues/3843
Instead of the previous AdaptationSet groupings that were done with the entire mime type with codecs parameter string and by audio track id, this pull request uses the mime type, codec without the level and profile information, the colour information and the audio track ids. This new grouping system will make sure that all AV1 and h264 streams go into one adaption set each, instead of a different one for every different profile and level, while making sure …

fix(toDash): Format grouping into AdaptationSets

---

src/parser/youtube/VideoInfo.ts

This pull request fixes a bug in #445. Turns out `caption_track_indices` is used to determine the order of the caption tracks in the UI, whereas `default_caption_track_index` refers to the original order of the caption tracks.
Noticed that the order can differ while digging into this video with broken audio track: https://youtu.be/UJeSWbR6W04 (the bug doesn't actually crop up for that video, as it has multiple audio tracks, so we don't need to dig around in the captions but it would have picked Portuguese instead of English for that video, if it did only have one audio track).

fix(Format): Extracting audio language from captions

---

src/utils/DashManifest.tsx

As pointed out by @absidue 
The DASH spec requires integer AdaptationSet ids
> specifies a unique identifier for this Adaptation Set in
the scope of the Period. The attribute shall be a unique
unsigned integer value in the scope of the containing
Period.

fix: invalid set ids in dash manifest

---

src/parser/classes/C4TabbedHeader.ts
src/parser/classes/ChannelHeaderLinksView.ts
src/parser/classes/VideoSecondaryInfo.ts
src/parser/classes/misc/Text.ts
src/parser/nodes.ts

This seems to be the replacement for `ChannelHeaderLinks`, it appears on almost every channel, regardless of visitor ID, so I suspect there either wasn't an A/B test or it has already ended. I haven't removed `ChannelHeaderLinks`, just in case, but I'm pretty sure we can get rid of it, unless it is used on the non-web clients.

feat(parser): Add `ChannelHeaderLinksView`

---

src/core/Session.ts

Should have added this when we first implemented session data retrieval to be honest, it makes a request to YouTube's service worker and the data there can change or the request can just fail.

feat(Session): Add fallback for session data retrieval

---

src/parser/classes/misc/Format.ts

Due to a mistake in the boolean logic, the is_original property in the `Format` class was always been set to `true`, regardless of whether it is actually dubbed or descriptive.

fix(Format): Fix `is_original` always being `true`

---

src/core/Session.ts

This adds support for manually specifying the `onBehalfOfUser` property in the session's `Context.user`, which specifies which channel to use if multiple users are associated with the logged-in account. This can be optionally specified when creating an `Innertube` instance in the same way as `account_id` is. I think this is only relevant if you're using a cookie session.
Profiles are identified with what might be called a "Page ID":  when I use the account switcher in the YouTube UI to switch profiles, it's the I see in a redirect URL like `https://www.youtube.com/signin?action_handle_signin=true&authuser=0&pageid=<THIS CHANNEL ID>`, where we can see it referred to as `pageid`.

feat(Session): Add on_behalf_of_user session option

---

src/parser/generator.ts

Instead of checking `typeof value === 'object' && value !== null` in all 3 `if`s, this pull request moves it to an `if` surrounding all 3 `if`s.

perf(generator): Remove duplicate checks in `isMiscType`

---

src/core/Player.ts
src/parser/classes/misc/Format.ts
src/parser/parser.ts

Currently for web responses at least, the `adaptiveFormats` and the `formats` each share one n-param value (two in total), per `/player` call (`Innertube#getInfo` and `Innertube#getBasicInfo` in YouTube.js). This pull request introduces a response level cache, meaning that calling `.decipher` on `Format` objects from the same response multiple times, will now use the already deciphered n-param, as long as it is the same as one of the ones in the cache. The way it is designed, it doesn't make any assumptions on the number of n-param values, so if YouTube starts using a unique one for every URL, this code will continue to work, it will just make the cache useless.
In my testing this resulted in the `toDash` function being on average more than 50% faster.

perf: Cache deciphered n-params by info response

---

src/parser/classes/livechat/UpdateViewershipAction.ts

`original_view_count` contains the number of current viewers as a number
`unlabeled_view_count_value` contains the formatted number of current viewers without the "watching now" text

feat(UpdateViewerShipAction): Add `original_view_count` and `unlabeled_view_count_value`

---

src/core/mixins/MediaInfo.ts

YouTube.js doesn't support generating DASH manifest for live and Post-Live-DVR videos, so now we'll throw an error that points people towards using the dash_manifest_url and hls_manifest_url that are already provided by YouTube.
YouTube.js also doesn't support downloading those videos, because they consist of 5 segment chunks that are all individual files, so they require stitching together with ffmpeg and can't just be written back to back into the same file.
closes #518

chore(MediaInfo): Throw helpful errors when calling toDash or download for live and Post-Live DVR videos

---

.github/workflows/lint.yml
.github/workflows/release-please.yml
.github/workflows/test.yml
package-lock.json
package.json

- Resolves the peer dependency conflict issue caused by #509.

feat: use `overrides` instead of `--legacy-peer-deps`

---

src/parser/classes/ChannelExternalLinkView.ts
src/parser/classes/ContentPreviewImageView.ts
src/parser/classes/HighlightsCarousel.ts
src/parser/classes/MusicLargeCardItemCarousel.ts
src/parser/classes/VideoAttributeView.ts
src/parser/classes/misc/Thumbnail.ts

`sources` seems to be the replacement for the `thumbnails` property, as the content is the same. This pull request adds support for parsing that in `Thumbnail.fromResponse`.

feat(Thumbnail): Support `sources` in `Thumbnail.fromResponse`

---

src/parser/generator.ts

When there is only one valid type being passed to `Parser.parseItem` or `Parser.parse`, it can be passed directly without being wrapped in an array, this pull request changes the generated output to only use an array when it is needed.
```js
// before
this.abc = Parser.parseItem(data.abc, [ YTNodes.AbcView ])
this.abc2 = Parser.parseItem(data.abc2, [ YTNodes.AbcView, YTNodes.AbcdView ])
// afterwards
this.abc = Parser.parseItem(data.abc, YTNodes.AbcView)
this.abc2 = Parser.parseItem(data.abc2, [ YTNodes.AbcView, YTNodes.AbcdView ])
```

fix(generator): Output Parser.parseItem() calls with one valid type, without the array

---

src/parser/generator.ts

Now that YouTube is using ViewModel nodes more often, it makes sense for the generator to be able to handle them.

feat(generator): Add support for generating view models

---

src/parser/youtube/VideoInfo.ts

Turns out the properties I was using before, are influenced by the language you request the page in and have nothing to do with the language of the audio. Instead we need to check the language of the auto-generated captions track, because that is generated in the language of the audio, yt-dlp does the same.
The video provided in https://github.com/LuanRT/YouTube.js/discussions/488 can be used to demonstrate the issue with the code below. It previously printed `en` but will correctly print `ru`, with this change. The video in question is in Russion, but because it has an English caption track and we requested the page in English, YouTube makes the English caption track the default.
```js
import { Innertube } from './dist/src/platform/node.js';
const session = await Innertube.create({ lang: …
```

fix(Format): Extract correct audio language from captions

---

src/parser/classes/DislikeButtonView.ts
src/parser/classes/LikeButtonView.ts
src/parser/classes/SegmentedLikeDislikeButtonView.ts
src/parser/classes/ToggleButtonView.ts
src/parser/nodes.ts
src/parser/youtube/VideoInfo.ts

This pull request adds support for YouTube's new like and dislike nodes. This also fixes the like count not getting extracted.
I have not updated the `like`, `dislike` or `removeRating` functions, as those require using YouTube.js with a YouTube account, the `basic_info.is_liked` and `basic_info.is_disliked` properties have not being tested either.
closes #554

feat(parser): Support new like and dislike nodes

---

src/parser/generator.ts
src/parser/parser.ts

Adds better inference support for arrays to the YTNode generator.
Before:
```ts
class Test extends YTNode {
static type = 'Test';
array: {
0: {
key1: string
},
1: {
key1: string,
key2: boolean
}
};
constructor(data: RawNode) {
super();
this.array = {
0: {
key1: data.array.0.key1
},
1: {
key1: data.array.1.key1,
key2: data.array.1.key2
}
};
}
}
```
After:
```ts
class Test extends YTNode {
static type = 'Test';
array: {
key1: string,
key2?: boolean
}[];
constructor(data: RawNode) {
super();
this.array = data.array.map((item: any) => ({
key1: item.key1,
key2: Reflect.has(item, 'key2') ? item.key2 : undefined
}));
}
}
```

feat(generator): add support for arrays

---

src/utils/StreamingInfo.ts

YouTube doesn't provide any color information for the h264 streams in their API responses. Players like shaka-player treat streams with missing color information differently, so you end up with duplicate qualities in the quality selector. As the h264 files that YouTube offers always seem to be SDR, it's a pretty safe bet to hard code that into the DASH manifest generator.
Alternatively we could copy the color information from the `vp9` (not the `vp9.2`) streams, but we would have to do that before we apply the users format filter, it would also mean that it would only work if `vp9` formats exist and are passed in.

fix(toDash): Add missing transfer characteristics for h264 streams

---

src/parser/classes/PlaylistVideo.ts
src/parser/youtube/Playlist.ts

This should address some issues where the library would fetch the wrong continuation or even empty continuations.
**NOTE**: The solution in https://github.com/LuanRT/YouTube.js/commit/987f50604a0163f9a07091ce787995c6f6fddb75 no longer applies after this PR is merged, as empty continuations were all in `SectionList#contents`.  If you had any code in place to handle that error, it is safe to remove it after this PR is merged.
1. Added `style` to `PlaylistVideo`. This helps identifying if the video is just a recommendation (`PLAYLIST_VIDEO_RENDERER_STYLE_RECOMMENDED_VIDEO`) or part of the playlist. 
2. `Playlist#items` can only return `PlaylistVideo` nodes now. Its return type is`ObservedArray<PlaylistVideo>`.

refactor(Playlist): Ignore `ContinuationItem` nodes from `SectionList#contents`

---

src/utils/Constants.ts

YouTube.js sending an old client version is the cause of the HTTP 500 errors that YouTube was returning, it also resulted in YouTube not returning the profile picture and banner for user channels in the PageHeader.

chore(Constants): Update web client version

---

src/parser/classes/ImageBannerView.ts
src/parser/classes/PageHeaderView.ts
src/parser/nodes.ts

Adds support for banners in `PageHeaderView`, requires #582 for YouTube to send the banner.

feat(parser): Add `ImageBannerView`

---

src/core/mixins/MediaInfo.ts
src/parser/classes/PlayerLiveStoryboardSpec.ts
src/parser/classes/PlayerStoryboardSpec.ts
src/utils/DashManifest.tsx
src/utils/StreamingInfo.ts

While YouTube does provide DASH manifests for Post Live DVR videos, those are limited to only the last few hours of the live stream. YouTube has also been known to return broken DASH manifests for Post Live DVR videos e.g. saying that a 12 hour long video is 4 hours long but that the segments start at hour 9 (logically the offset cannot be larger than the entire video is supposed to be).
Post Live DVR videos can be found by using the script in the testing section here: https://github.com/FreeTubeApp/FreeTube/pull/3872
BREAKING CHANGES: The `duration` property in `StreamingInfo` has been replaced by the asynchronous `getDuration()` function, as getting the duration of Post Live DVR videos requires making a fetch request.

feat(toDash)!: Add support for generating manifests for Post Live DVR videos

---

src/parser/classes/DescriptionPreviewView.ts
src/parser/youtube/Channel.ts

This is a follow up to #577.
Turns out that it is possible to get the about popup for user channels with a `PageHeader` header, it's buried in `rendererContext.commandContext` though, which usually only contains tracking data.
In the mean time I've also realised that it is possible to get the channel avatar from the channel metadata, so while it's not in the header at least it is still available.
A lot of the structure here is pretty similar to the one in `ChannelTagline`, so at some point it might be worth refactoring that out into it's own class, to reduce the duplicate code.

feat(Channel): Support getting about with PageHeader

---

src/parser/classes/PlayerCaptionsTracklist.ts

`undefined` -> standard
`'asr'` -> automatic speech recognition
`'frc'` -> forced

fix(PlayerCaptionTracklist): Fix `captions_tracks[].kind` type

---

src/parser/classes/misc/Format.ts
src/utils/FormatUtils.ts

Live streams that have captions, have them listed in the `adaptiveFormats` instead of the captions tracklist renderer. This pull request adds support for those. The caption track streams themselves are MP4 files that contain subtitles in YouTube's srv3 xml format.
https://youtube.com/@NBCNews/streams tends to regularly have live streams with captions. (unfortunately setting the search filters to live and CC, returns a bunch of live streams that are tagged with CC but don't have any subtitles or captions, so I just had to keep looking until I found videos with them).

feat(Format): Support caption tracks in adaptive formats

---

src/parser/classes/LockupView.ts

I accidentally left some `console.log` calls that I had used for debugging in #609.

chore(LockupView): Remove debug logging

---

examples/comments/README.md
examples/livechat/README.md

There were apostrophes in the links which caused them to produce 404s. See the issues by clicking the bottommost link (`See index.ts here`):
- https://github.com/LuanRT/YouTube.js/tree/main/examples/comments
- https://github.com/LuanRT/YouTube.js/tree/main/examples/livechat

Fix broken README links

---

src/core/Session.ts
src/core/endpoints/PlayerEndpoint.ts
src/proto/generated/messages/youtube/(ShortsParam)/Field1.ts
src/proto/generated/messages/youtube/(ShortsParam)/index.ts
src/proto/generated/messages/youtube/ShortsParam.ts
src/proto/generated/messages/youtube/index.ts
src/proto/index.ts
src/proto/youtube.proto
src/utils/Constants.ts
src/utils/HTTPClient.ts
test/main.test.ts

To fix this, I modified the protobuf parameter we were using from:
```
{
"1": {
"2": 6
},
"59": 1
}
```
To:
```
{
"1": {
"1": 1
},
"59": 1
}
```
This is probably a temporary solution but it seems to work fine for now. 
Unless you can't run our JavaScript interpreter ([Jinter](https://github.com/LuanRT/Jinter)), I recommend using the WEB client (default)  for something more stable.
Run the following code and try to play the streaming URL in a browser.
```ts
import { Innertube } from 'youtubei.js';
const yt = await Innertube.create();
const videoInfo = await yt.getBasicInfo('ksEYRaIpP7A', 'ANDROID');
console.info("Playback URL:", videoInfo.streaming_data.formats.find((stream) => stream.quality_label == '720p').url);
```
Related:
https://github.com/LuanRT/YouTube.js/issues/623, …

fix(PlayerEndpoint): Workaround for "The following content is not available on this app" (Android)

---

examples/cloudflare-worker/package.json
examples/cloudflare-worker/src/index.ts
examples/cloudflare-worker/tsconfig.json
examples/cloudflare-worker/wrangler.toml
package.json
src/platform/cf-worker.ts
src/types/PlatformShim.ts
src/utils/HTTPClient.ts

HI thank you for you work 😄 ,
I resolved two problems that are needed to make the lib work in cloudflare workers runtime:
- removed `credentials` http header which is not available
- changed the way that the global `fetch` function is passed to the `Platform` class
And I have implemented the cache for cloudflare workers

feat: add support of cloudflare workers runtime

---

src/parser/classes/misc/Format.ts

* `projection_type` is used for 360/VR videos. Test videos here: https://www.youtube.com/@360
* `stereo_layout` is used for 3D videos. Test videos here: https://www.youtube.com/3d

feat(Format): Add `projection_type` and `stereo_layout`

---

src/utils/Constants.ts
src/utils/HTTPClient.ts

YouTube's website no longer sends the `X-Origin` header, they do however send a `X-Youtube-Client-Name` header that contains a number (presumably it's an enum in their backend).
They also send a `X-Youtube-Bootstrap-Logged-In: false` header, but as I'm not sure what the equivalent is for logged in users, I decided not to add that.
I sucessfully tested this with the web and tv embed clients.

chore(HTTPClient): Add X-Youtube-Client-Name and remove X-Origin headers

---

src/parser/classes/misc/Format.ts

YouTube is currently A/B testing Stable Volume on the website, it's been in the iOS and Android apps since summer 2023. The audio streams with stable volume, can be identified through the `is_drc` property. DRC stands for Dynamic Range Compression. The WEB client has had Dynamic Range Compression on very specific videos for a long time, since before Stable Volume was a feature on mobile. Here is yt-dlp's test case for DRC streams (age-restricted): https://www.youtube.com/watch?v=Tq92D6wQ1mg (https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/youtube.py#L2629)
I'll be doing a follow-up pull request that adds support to the `toDash` function to treat the DRC streams as a separate audio track.

feat(Format): Add `is_drc`

---

src/core/mixins/MediaInfo.ts
src/types/DashOptions.ts
src/types/StreamingInfoOptions.ts
src/utils/DashManifest.tsx
src/utils/StreamingInfo.ts

See https://github.com/LuanRT/YouTube.js/pull/656 for more information about Stable Volume/DRC.
This pull request makes `toDash` treat DRC and non-DRC streams as a separate audio tracks, that will make most players, show their audio track selector so that you can switch between them, instead of counting them all as the same audio track. As the generated labels are user facing, I decided to allow the caller of the `toDash` method, to override the default ones if they want to, that allows the labels to be translated (we don't need this for the normal multiple audio track labels, as you can change the request language to YouTube to get translated labels).
YouTube doesn't return DRC streams for videos with multiple audio tracks at the moment, however I still decided to add support for that, …

feat(toDash): Add support for stable volume/DRC

---

src/core/Actions.ts
src/core/Player.ts
src/core/Session.ts
src/utils/LZW.ts
src/utils/index.ts

This adds cache for sessions and LZW compressions to reduce the size of the cache files.

perf(general): Add session cache and LZW compression

---

src/core/Session.ts

This is `true` by default.
See https://github.com/LuanRT/YouTube.js/pull/663#issuecomment-2146161637

feat(Session): Add `enable_session_cache` option

---

package.json
src/platform/README.md
src/platform/react-native.md
src/platform/react-native.ts
src/types/PlatformShim.ts

Following PR adds support for `react-native` as a target platform. Thank you for making the library platform-agnostic and including the guide on how to add support for a new one – it helped a ton!
I've added some docs explaining what steps need to be taken on RN side in order for things to work.
There are some rough edges around typing that could easily be fixed. Decided to throw it up here first to get some feedback.

Add support for `react-native` platform

---

src/utils/StreamingInfo.ts

SegmentTemplate durations are supposed to be unsigned integers, as the toDash function was generating image representations that had float durations, it broke the thumbnails display in recent versions of shaka-player.

fix(toDash): Fix image representations not being spec compliant

---

src/core/mixins/MediaInfo.ts
src/parser/classes/PlayerCaptionsTracklist.ts
src/types/StreamingInfoOptions.ts
src/utils/DashManifest.tsx
src/utils/StreamingInfo.ts

By default no captions get included in the DASH manifest, however if the video has captions, the developer can ask for them to be included by setting the new `captions_format` option to either `vtt` or `ttml` depending on which format they would like.
To avoid making extra requests, this hardcodes the bandwidth/bitrate of the text adaptation sets to `0`.
I tested that this works with shaka-player, I haven't tested it with any other players.

feat(toDash): Add option to include WebVTT or TTML captions

---

src/utils/FormatUtils.ts

This is fix for catch error when response status is not 2XX.
There are throw of 'not 2XX' in 'video+audio' type already, but not in other type.
So I meet some problem when youtube give 403 status ('audio' type), I cannot catch any error and download function is stopped.
This change is for catching error in above case.

fix(FormatUtils): Throw an error if download requests fails

---

src/utils/DashManifest.tsx
src/utils/StreamingInfo.ts

You can ask YouTube to translate a caption track with machine translation by adding the `tlang` query parameter with your desired locale. This pull request adds to `dub` role to those caption tracks when adding them to the DASH manifest.
Unfortunately there doesn't seem to be a suitable role value in the `urn:mpeg:dash:role:2011` scheme for auto-generated captions (`kind=asr`), so we don't currently have a way to tag those inside the DASH manifest, unless we want to create a custom scheme.

feat(toDash): Add the "dub" role to translated captions

---

package-lock.json
package.json
src/core/Player.ts
src/platform/jsruntime/jinter.ts

This pull request adds support for the player `b22ef6e7`, which uses `String.prototype.split` and `Array.prototype.join`.
A Jinter update will be required to add support for `Array`.

fix(Player): Fix extracting the n-token decipher algorithm

---

src/proto/generated/messages/youtube/(GetCommentsSectionParams)/(Params)/Options.ts
src/proto/index.ts
src/proto/youtube.proto

The `proto.encodeCommentSectionParams` method now has a new optional parameter called `comment_id`, which allows highlighting a specific comment when the page is opened. Here is an example code snippet:
```javascript
//continuation for /watch?v=jlAd027IBsc&lc=Ugxvmarhks-D40zwQKJ4AaABAg
const continuation = encodeCommentsSectionParams(
"jlAd027IBsc",
{
comment_id: "Ugxvmarhks-D40zwQKJ4AaABAg"
}
);
console.log(continuation);
```
The output of the above code will be:
```
Eg0SC2psQWQwMjdJQnNjGAYyQiIuIgtqbEFkMDI3SUJzYzAAeAKCARpVZ3h2bWFyaGtzLUQ0MHp3UUtKNEFhQUJBZ0IQY29tbWVudHMtc2VjdGlvbg%3D%3D
Process finished with exit code 0
```
---

feat(proto): Add `comment_id` to commentSectionParams

---

src/core/Player.ts

Alternative to https://github.com/LuanRT/YouTube.js/pull/698 which maintains backwards compatibility in case YouTube switches back to their previous two versions of the function.

fix(Player): Fix extracting the n-token decipher algorithm again

---

src/core/Player.ts

We should always do this after updating the sig/nsig code. It's so that the old cache gets ignored : ).

fix(Player): Bump cache version

---

src/parser/classes/EomSettingsDisclaimer.ts
src/parser/nodes.ts

This is needed when the `cookie` option is used in Node.js:
```typescript
const youtube = await Innertube.create({
cookie: 'xxx',
});
const history = await youtube.getHistory()
console.log(history.feed_actions.contents.at(-1))
```
```javascript
EomSettingsDisclaimer {
type: 'EomSettingsDisclaimer',
disclaimer: Text {
runs: [ [TextRun], [TextRun], [TextRun] ],
text: 'These settings are not available because of your current cookies selections. If you prefer to turn on your watch & search history, you can do so by managing your cookies at any time.'
},
info_icon: { icon_type: 'INFO' },
usage_scenario: 'EOM_EXIT'
}
```
Interestingly, valid browser cookies give a different response but no history:
```javascript
EomSettingsDisclaimer {
type: 'EomSettingsDisclaimer',
disclaimer: Text {
runs: [ …
```

feat(parser): Add `EomSettingsDisclaimer` node

---

package-lock.json
package.json
src/core/Player.ts
src/utils/Utils.ts

Notes:
- The Syntax Tree is generated by [Jinter](https://github.com/LuanRT/Jinter) (which is built on top of [Acorn](https://github.com/acornjs/acorn)).
- While doing this may be slightly slower than using a regular exp, it is much more reliable (plus we already cache the player functions anyway).
- `findFunction` expects the functions to be inside a self-invoking function.
```ts
export type FindFunctionArgs = {
/**
* The name of the function.
*/
name?: string;
/**
* A string that must be included in the function's code for it to be considered.
*/
includes?: string;
/**
* A regular expression that the function's code must match.
*/
regexp?: RegExp;
};
````
```ts
const source = '(function() {var foo, bar; foo = function() { console.log("foo"); }; bar = function() { console.log("bar"); }; …
```

refactor(Player): Generate and parse player script's `AST`

---

src/parser/youtube/Search.ts

YouTube seems to have two types of search responses, one of them consists of a single `ItemSection` and then the continuation, the second type is made up of lots of `ItemSection`s each with only a few number of items in them and then the continuation. To be able to handle both cases, I've changed the code to merge together the items from all of the sections. This shouldn't cause any problems, as the `People also watched` and `People also search for` sub-sections are shelves (`Shelf` class) inside of the `ItemSection`s.
https://github.com/FreeTubeApp/FreeTube/issues/5510

fix(Search): Fix it occasionally returning only a small number of results

---

src/core/Session.ts

This is fir for missing potoken in player request's payload.
After that fix, then potoken is works so I don't see 'sign in~bot' error.

fix(Session): PoToken not being set correctly

---

src/core/Session.ts

When generating the session remotely without passing in visitor data, it was incorrectly using an empty string instead of falling back to the visitor data generated by YouTube.

fix(Session): Fix remote visitor data not gettting used

---

src/parser/classes/ThumbnailBadgeView.ts

Fixes the parser error caused by `ThumbnailBadgeView` assuming that the `icon_name` is always available.

fix(parser): The icon_name property does not always exist in ThumbnailBadgeView

---

protos/generated/misc/params.ts
protos/misc/params.proto
src/utils/ProtoUtils.ts

This makes it possible to do the API equivalent of https://www.youtube.com/watch_videos?video_ids=jNQXAC9IVRw,9bZkp7q19f0, by sending that protobuf as the `params` in the `/next` API call.

feat(ProtoUtils): Add support for creating NextParams

---

src/parser/classes/Shelf.ts

This PR adds support for an optional subtitle property for the Shelf object.
An example of this can be found on Linus Tech Tips home page with the "As Fast As Possible" shelf:

feat(Parser): Add support for parsing subtitle for `Shelf`

---

src/parser/classes/livechat/items/LiveChatSponsorshipsGiftPurchaseAnnouncement.ts
src/parser/classes/livechat/items/LiveChatSponsorshipsHeader.ts
src/parser/nodes.ts

Add a new parser for the live chat node that appears when someone sends gifted memberships.
```json
{
"liveChatSponsorshipsGiftPurchaseAnnouncementRenderer": {
"id": "ChwKGkNKdUVzTmJRbW9rREZZMlY1UWNkU3dJSDZ3",
"timestampUsec": "1729347301072447",
"authorExternalChannelId": "UCnkXGpBlY-1aJGuQASWs1gw",
"header": {
"liveChatSponsorshipsHeaderRenderer": {
"simpleText": "Lance蘭斯"
},
{
"url": "https://yt4.ggpht.com/1ghjNFZV9AH4fOlq2eJYS7SG0z_VuBm7zKINkYZdxJ3_edCLhqYfNw-YfbcSzAg7QCnQ_XtB=s32-c-k-c0x00ffffff-no-rj",
"width": 32,
"height": 32
},
{
"url": "https://yt4.ggpht.com/1ghjNFZV9AH4fOlq2eJYS7SG0z_VuBm7zKINkYZdxJ3_edCLhqYfNw-YfbcSzAg7QCnQ_XtB=s64-c-k-c0x00ffffff-no-rj",
"width": 64,
"height": 64
}
]
},
"primaryText": { …
```

feat(parser): Add `LiveChatSponsorshipsGiftPurchaseAnnouncement` and `LiveChatSponsorshipsHeader` nodes

---

src/parser/classes/livechat/items/LiveChatSponsorshipsGiftRedemptionAnnouncement.ts
src/parser/nodes.ts

Add a new parser for the live chat node that appears when someone receives a gifted membership.
```json
{
"liveChatSponsorshipsGiftRedemptionAnnouncementRenderer": {
"id": "ChwKGkNMcXYzWlhtbFlrREZiSXUxZ0FkeFVjVHF3",
"timestampUsec": "1729181259381482",
"timestampText": {
"simpleText": "2:04:31"
},
"authorExternalChannelId": "UCEEweFt_lPNNTiwSU3Z--jg",
"simpleText": "Atama Hikari 光頭 Ch."
},
{
"url": "https://yt4.ggpht.com/KdYuzSiJbBJZv_bmz-TdabkHbactoCrNXnuC7OuBmxsG3jYMZMZZNTRsBimVZB84TDWK4pXLYg=s32-c-k-c0x00ffffff-no-rj",
"width": 32,
"height": 32
},
{
"url": "https://yt4.ggpht.com/KdYuzSiJbBJZv_bmz-TdabkHbactoCrNXnuC7OuBmxsG3jYMZMZZNTRsBimVZB84TDWK4pXLYg=s64-c-k-c0x00ffffff-no-rj",
"width": 64,
"height": 64
}
]
}, …
```

feat(parser): Add `LiveChatSponsorshipsGiftRedemptionAnnouncement` node

---

src/parser/classes/LockupView.ts

Since I originally added the node it looks like there are a lot more possible types, this pull request adds the missing ones.

fix(parser): Update list of possible content_type in LockupView

---

src/parser/classes/AvatarView.ts

`AvatarView`s in watch next responses don't have the image processor.

fix(parser): The AvatarView.image_processor property is optional

---

src/parser/classes/RichShelf.ts

This PR adds support for an optional subtitle property for the RichShelf object.
Example channel that could have it:
https://www.youtube.com/channel/UCtFRv9O2AHqOZjjynzrv-xg

feat(Parser): Add support for parsing subtitle for `RichShelf`

---

src/parser/classes/LockupMetadataView.ts

LockupView with the `content_type` `VIDEO` can sometimes have a channel avatar in their metadata.

feat(parser): Add optional image property to LockupMetadataView

---

src/core/managers/PlaylistManager.ts

This is a workaround for #800, while also enhancing the resilience of video removal. It improves upon #715 by making it more performant by not fetching the set video IDs again.
Similar changes could be applied to the `moveVideo` method as well.

Optimize playlist video removal

---

src/Innertube.ts
test/main.test.ts

As per https://github.com/LuanRT/YouTube.js/issues/797, I wanted a way to get the "Courses" from the "Explore" so I added a function. We have not made any significant changes.
To test this code, run the `getCourses` function and make sure `shelves` has the retrieved courses.

feat: Add `getCourses` function to get courses from explore.

---

src/parser/classes/livechat/items/LiveChatModeChangeMessage.ts
src/parser/nodes.ts

```json
{
"liveChatModeChangeMessageRenderer": {
"id": "ChwKGkNQdTQwcFd1MVBZQ0ZTVU01d29kX2NNTW1R",
"timestampUsec": "1647768006658253",
"icon": {
"iconType": "TAB_SUBSCRIPTIONS"
},
"text": {
"runs": [
{
"text": "庫洛姆•Kuromu",
"bold": true
},
{
"text": " turned on subscribers-only mode",
"bold": true
}
]
},
"subtext": {
"runs": [
{
"text": "Only channel subscribers of ",
"italics": true
},
{
"text": "5 minutes",
"italics": true
},
{
"text": " or longer can send messages",
"italics": true
}
]
},
"timestampText": {
"simpleText": "18:29"
}
}
}
```
Example RawNode data 2:
```json
{
"liveChatModeChangeMessageRenderer": {
"id": "ChwKGkNQVzYwcFd1MVBZQ0Zlc2VyUVlkV1JVQ2Nn",
"timestampUsec": "1647768006657834",
"icon": {
"iconType": "QUESTION_ANSWER"
},
"text": {
"runs": [
{ …
```

feat(parser): add `LiveChatModeChangeMessage` node

---

src/parser/classes/Channel.ts
src/parser/classes/ChannelAboutFullMetadata.ts
src/parser/classes/ChannelVideoPlayer.ts
src/parser/ytmusic/Search.ts

These getters have been marked as deprecated for a long tme and many of them logged warnings when they were used, so I think it is okay to remove them now.

chore(parser)!: Remove getters that have been deprecated for a long time

---

src/parser/helpers.ts
src/platform/web.ts
src/utils/Log.ts
src/utils/StreamingInfo.ts
src/utils/Utils.ts
src/utils/index.ts

This pull request converts the logger from a class to a module, as all methods and properties in the logger class were static, there was no real reason to keep it as a class. In FreeTube this shaved 889 bytes off the bundle, I know it's not much but it is something. It also meant that terser was able to inline the number values from the `Level` object to where they are used, which avoid having to look them up in the object at runtime.
I've marked this as a breaking change just in case someone was using the `Log` class as a type, but any code to use the logger outside of YouTube.js e.g. to set the log level can stay the same. If you feel like this doesn't warrant being a breaking change, I am happy to adjust the commit message and pull request title to remove the `!`.
If you are used to …

feat(Log)!: Convert Log class to module

---

src/parser/classes/PageHeaderView.ts

This field is used for the channel thumbnail on some system channels such as `https://youtube.com/gaming` and `https://youtube.com/learning` the thumbnail links point to animated WebP images.

feat(parser): Add `animated_image` to `PageHeaderView`

---

src/utils/Constants.ts

The hardcoded version is over 11 months old and as some fields are not returned for older versions, I decided to update it.

chore(Utils): Bump WEB version constant to latest version

---

src/core/Session.ts
src/core/managers/AccountManager.ts
src/parser/classes/ChannelSwitcherHeader.ts
src/parser/classes/ChannelSwitcherPage.ts
src/parser/classes/actions/UpdateChannelSwitcherPageAction.ts
src/parser/nodes.ts
src/utils/HTTPClient.ts

Currently, `on_behalf_of_user`  arg seems to have no effect at all. This PR fixes that. So, for instance, the following works:
```
const innertube = await Innertube.create({
cookie,
on_behalf_of_user: pageIdToken
});
```
To determine the value of `pageIdToken` above, we obtain the full list of channels belonging to the account. Currently, `AccountManager` provides `getInfo()` that only retrieves the active channel info. This PR overloads that method to include fetching the full list of channels, so we can easily obtain the value of `pageIdToken` to facilitate channel-switching:
```
const innertube = await Innertube.create({ cookie });
const channels = await innertube.account.getInfo(true);
const active = channels.find((ac) => ac.is_selected);
if (!active) {
throw Error('No active channel …
```

refactor: Cookie-based session fixes and minor additions

---

src/parser/classes/ClientSideToggleMenuItem.ts
src/parser/nodes.ts

Fixes #595 
Fixes #727 
```json
{
"clientSideToggleMenuItemRenderer": {
"defaultText": {
"runs": [
{
"text": "Timestamps"
}
]
},
"defaultIcon": {
"iconType": "ACCESS_TIME"
},
"toggledText": {
"runs": [
{
"text": "Timestamps"
}
]
},
"toggledIcon": {
"iconType": "ACCESS_TIME"
},
"menuItemIdentifier": "timestamp_toggle",
"command": {
"clickTrackingParams": "CAYQl98BIhMI7bKs8KG9iQMVWaPYBR2lDhra",
"toggleLiveChatTimestampsEndpoint": {
"hack": true
}
}
}
}
```
Example RawNode data 2:
```json
{
"clientSideToggleMenuItemRenderer": {
"defaultText": {
"runs": [
{
"text": "Reactions"
}
]
},
"defaultIcon": {
"iconType": "HEART_CIRCLE"
},
"toggledText": {
"runs": [
{
"text": "Reactions"
}
]
},
"toggledIcon": {
"iconType": "HEART_CIRCLE"
},
"isToggled": true, …
```

feat(parser): Add `ClientSideToggleMenuItem`

---

src/parser/youtube/VideoInfo.ts

For movie trailers, PlayerLegacyDesktopYpcTrailer still seems to be used but I found an upcoming livestream that had a trailer associated with it and it used a YpcTrailer directly

feat(Parser): Parse YpcTrailer in VideoInfo

---

src/parser/classes/livechat/ReplaceLiveChatAction.ts
src/parser/nodes.ts

```json
{
"clickTrackingParams": "CAEQl98BIhMIiZDZ06iligMVU1n1BR0gthYd",
"replaceLiveChatRendererAction": {
"toReplace": "REPLACE_LIVE_CHAT_ACTION_PANEL",
"replacement": {
"liveChatRestrictedParticipationRenderer": {
/* truncated */
}
}
}
}
```

feat(parser): Add `ReplaceLiveChatAction`

---

src/parser/classes/commands/GetKidsBlocklistPickerCommand.ts
src/parser/classes/endpoints/AddToPlaylistServiceEndpoint.ts
src/parser/classes/endpoints/BrowseEndpoint.ts
src/parser/classes/endpoints/CreateCommentEndpoint.ts
src/parser/classes/endpoints/CreatePlaylistServiceEndpoint.ts
src/parser/classes/endpoints/DeletePlaylistEndpoint.ts
src/parser/classes/endpoints/FeedbackEndpoint.ts
src/parser/classes/endpoints/GetAccountsListInnertubeEndpoint.ts
src/parser/classes/endpoints/LikeEndpoint.ts
src/parser/classes/endpoints/LiveChatItemContextMenuEndpoint.ts
src/parser/classes/endpoints/ModifyChannelNotificationPreferenceEndpoint.ts
src/parser/classes/endpoints/PerformCommentActionEndpoint.ts
src/parser/classes/endpoints/PlaylistEditEndpoint.ts
src/parser/classes/endpoints/ReelWatchEndpoint.ts
src/parser/classes/endpoints/SearchEndpoint.ts
src/parser/classes/endpoints/ShareEntityServiceEndpoint.ts
src/parser/classes/endpoints/SubscribeEndpoint.ts
src/parser/classes/endpoints/UnsubscribeEndpoint.ts
src/parser/classes/endpoints/WatchEndpoint.ts
src/parser/classes/endpoints/WatchNextEndpoint.ts

Hoisting these constants into normal variables results in a shaved 1053 bytes off FreeTube's bundle size, as it didn't require the private property polyfill and was able to inline the constants, as they are only used once. I didn't inline them in the source code to allow server side apps that likely handle a lot more requests and don't use bundling benefit from only needing to initialise those strings once.

chore(parser): Hoist API_PATH constants in endpoint nodes

---

src/parser/classes/livechat/items/BumperUserEduContentView.ts
src/parser/classes/livechat/items/LiveChatItemBumperView.ts
src/parser/classes/livechat/items/LiveChatPaidMessage.ts
src/parser/nodes.ts

When a viewer donates for the 1st, 3rd, 5th, 10th, or 20th time, there will be a special type of `LiveChatPaidMessage` that includes an animated image in the header, followed by a bumper text message.
```json
{
"liveChatPaidMessageRenderer": {
"id": "ChwKGkNNLW5qY3lHcVlvREZUWER3Z1FkcHY4MEhn",
"timestampUsec": "1734240867193101",
"simpleText": "Alice Phi - 小ㄈㄞ"
},
{
"url": "https://yt4.ggpht.com/A-kvvyBXNbkhlBQPKwkVqBD1dYoG5l4licWKpSYseFMcYHsK8kpnTGpGBPpT6SoT_xmI3RRExg=s32-c-k-c0x00ffffff-no-rj",
"width": 32,
"height": 32
},
{
"url": "https://yt4.ggpht.com/A-kvvyBXNbkhlBQPKwkVqBD1dYoG5l4licWKpSYseFMcYHsK8kpnTGpGBPpT6SoT_xmI3RRExg=s64-c-k-c0x00ffffff-no-rj",
"width": 64,
"height": 64
}
]
},
"purchaseAmountText": { …
```

feat(LiveChatPaidMessage): Parse `headerOverlayImage` and `lowerBumper`

---

src/parser/youtube/LiveChat.ts

Fixes #853 
Handle the case when `RunAttestationCommand` is included in the `sendMessage()` response actions.
Example response data:
```json
{
"responseContext": {
/* truncated */
},
"actions": [
{
"clickTrackingParams": "IhMIyYG6_ezFigMVXfJMAh0nvgZN",
"addChatItemAction": {
"item": {
"liveChatTextMessageRenderer": {
"message": {
"runs": [
{
"text": "hi"
}
]
},
"simpleText": "YOLO9487"
},
{
"url": "https://yt4.ggpht.com/--MMwR8If9UU6Fk0ldP817V-HIC8MfIcbfncUoXYKWehJ1pDHev5OvRj4mtS-0yStMUQ28xj7Xs=s32-c-k-c0x00ffffff-no-rj",
"width": 32,
"height": 32
},
{
"url": "https://yt4.ggpht.com/--MMwR8If9UU6Fk0ldP817V-HIC8MfIcbfncUoXYKWehJ1pDHev5OvRj4mtS-0yStMUQ28xj7Xs=s64-c-k-c0x00ffffff-no-rj",
"width": 64,
"height": 64
}
]
},
"contextMenuEndpoint": { …
```

fix(sendMessage): Handle `RunAttestationCommand` in response actions

---

src/parser/classes/ButtonCardView.ts

Fix the typo introduced in #834
The data field should be `data.image` rather than `data.icon`.

fix(ButtonCardView): correct typo

---

src/parser/youtube/VideoInfo.ts

Follow-up to #842
`YTNode#is()` is seen as a type guard by TypeScript so we don't need to cast it again with `YTNode#as`. I also removed some unnecessary optional chaining operators.

chore(parser): Simplify VideoInfo#getTrailerInfo

---

src/parser/classes/livechat/items/LiveChatTextMessage.ts

Update `LiveChatTextMessage` to extend `YTNode` rather than `LiveChatMessageBase` to better align with the latest data provided by Innertube.
- Add `timestamp_usec` property
- Add `timestamp_text` property
- Add `context_menu_accessibility_label` property
- Add `before_content_buttons` property
Example response data 1:
```json
{
"liveChatTextMessageRenderer": {
"message": {
"runs": [
{
"text": "嫩 "
}
]
},
"simpleText": "ùwú"
},
{
"url": "https://yt4.ggpht.com/ytc/AIdro_k1IuACuxzZhNjtZ2wv7NVcvzDTOy60pZM3jMnX2S3rRRQ=s32-c-k-c0x00ffffff-no-rj",
"width": 32,
"height": 32
},
{
"url": "https://yt4.ggpht.com/ytc/AIdro_k1IuACuxzZhNjtZ2wv7NVcvzDTOy60pZM3jMnX2S3rRRQ=s64-c-k-c0x00ffffff-no-rj",
"width": 64,
"height": 64
}
]
},
"contextMenuEndpoint": { …
```

feat(parser): Update `LiveChatTextMessage`

---

src/parser/classes/ContentMetadataView.ts

```json
{
"contentMetadataViewModel": {
"metadataRows": [
{
"metadataParts": [
{
"text": {
"content": "@pbsspacetime",
"styleRuns": [
{
"weightLabel": "FONT_WEIGHT_MEDIUM",
"styleRunExtensions": {
"styleRunColorMapExtension": {
"colorMap": [
{
"key": "USER_INTERFACE_THEME_LIGHT",
"value": 4279440147
},
{
"key": "USER_INTERFACE_THEME_DARK",
"value": 4294967295
}
]
}
}
}
]
},
"enableTruncation": true
}
]
}
],
"delimiter": "•"
}
}
```

feat(ContentMetadataView): Parse `enableTruncation`

---

src/parser/classes/misc/Text.ts

Fixes #850
Fixes #854
In AttributedText, styleRuns may not always include the `startIndex` or `length` properties
- If `startIndex` is missing, we assume the style applies from the beginning of the text
- If `length` is missing, we assume the style applies to the entire text
```json
{
"contentMetadataViewModel": {
"metadataRows": [
{
"metadataParts": [
{
"text": {
"content": "@pbsspacetime",
"styleRuns": [
{
"weightLabel": "FONT_WEIGHT_MEDIUM",
"styleRunExtensions": {
"styleRunColorMapExtension": {
"colorMap": [
{
"key": "USER_INTERFACE_THEME_LIGHT",
"value": 4279440147
},
{
"key": "USER_INTERFACE_THEME_DARK",
"value": 4294967295
}
]
}
}
}
]
},
"enableTruncation": true
}
]
}
],
"delimiter": "•"
}
}
```

fix(Text#fromAttributed): Fix `StyleRun` assuming that the `startIndex` and `length` always exist

---

src/core/clients/Music.ts
src/parser/types/ParsedResponse.ts
src/parser/ytmusic/TrackInfo.ts
test/main.test.ts

The changes add a function to get a continuation of the UpNext PlaylistPanel or PlaylistPanelContinuation.
Therefore a further test was added. :)

feat(Music): Add continuation support for "Up next" tab in `TrackInfo`

---

src/Innertube.ts
src/core/Actions.ts
src/parser/parser.ts
src/parser/types/ParsedResponse.ts
src/parser/types/RawResponse.ts
src/types/Misc.ts

YouTube has recently started using this InnerTube endpoint to fetch challenges for WebPo generation.

feat(Innertube): Add `getAttestationChallenge`

---

src/utils/DashManifest.tsx
src/utils/DashUtils.ts

This pull request introduces various optimisations to DASH manifest generation. I have checked that the generated XML is still the same as before.
1. It turns out that the JSX transform only checks the first letter in the tag name to decided if it is an element (lower case) or a component/function (upper case). So I decided to change the tag names to be the same as their actual names but with the first letter changed to lower case, that way we can simplify the code in `normalizeTag` name to just change the first character to upper case.
2. For text nodes we currently create a `TEXT_ELEMENT` wrapper object and then give that `TEXT_ELEMENT` object special treatment in `renderElementToString` to treat it as a string. As our target is just a string and not some DOM like environment, I …

perf: Optimise DASH manifest generation

---

src/core/Session.ts
src/utils/HTTPClient.ts

Certain attestation challenges are bound to the user agent (e.g, WebPo), so we can't just use a random one for every request.

feat(Session): Allow using a fixed user agent for InnerTube requests

---

src/core/clients/Studio.ts
src/utils/Constants.ts
src/utils/HTTPClient.ts

Moving the client name IDs into their own object, allows us to simplify the lookups in HTTPClient to just being a property lookup, instead of using `Object.values()` and `Array#find()` to locate the correct client information. It is worth noting that unlike the `CLIENTS` object that uses user-friendly names as the keys, the new `CLIENT_NAME_IDS` object uses the real client names (the ones in the `NAME` fields in the `CLIENTS` object) to enable the quick lookup.

perf(constants): Move the client name IDs into their own `CLIENT_NAME_IDS` object

---

src/core/Session.ts
src/core/mixins/MediaInfo.ts
src/utils/Constants.ts

For people using bundlers and mimifiers this allows unused constants to be treeshaken and in the case of terser, it even goes a step further and hoists the strings out of the objects into their own variables. While yes this doesn't provide protection at runtime like the prior solution did, I think it is probably fair to say that if someone intentionally modifies the constants and things break, it is their own fault and developers using TypeScript still won't be able to modify them easily thanks to the `as const` assertion.

refactor(Constants): Use `as const` instead of `Object.freeze()`

---

src/types/FormatUtils.ts
src/utils/FormatUtils.ts

Fixes #871 
More specific format control is better, like filtering by itag or video/audio codec.

feat(FormatUtils): choose more specific format by itag or codec

---

src/core/Actions.ts
src/core/clients/Music.ts
src/core/mixins/Feed.ts
src/parser/classes/MusicResponsiveListItem.ts
src/parser/classes/comments/CommentThread.ts
src/parser/youtube/AccountInfo.ts
src/parser/youtube/Channel.ts
src/parser/youtube/HashtagFeed.ts
src/parser/youtube/History.ts
src/parser/youtube/HomeFeed.ts
src/parser/youtube/Library.ts
src/parser/youtube/NotificationsMenu.ts
src/parser/youtube/Playlist.ts
src/parser/youtube/Search.ts
src/parser/youtube/TranscriptInfo.ts
src/parser/youtube/VideoInfo.ts
src/parser/ytkids/Channel.ts
src/parser/ytkids/Search.ts
src/parser/ytmusic/Album.ts
src/parser/ytmusic/Artist.ts
src/parser/ytmusic/Library.ts
src/parser/ytmusic/Playlist.ts
src/parser/ytmusic/Search.ts
src/parser/ytmusic/TrackInfo.ts

As those `ObservedArray` helpers are just thin wrappers around `[0]` and `.find()` respectively. Using the original versions should be slightly faster and uses slightly less code, without losing any functionality.
It might be worth deprecating the `.first()`, `.matchCondition()` and `.remove()` helpers, because they all are just thin wrappers that don't provide any additional functionality than just interacting with the array yourself directly. Removing them straight away might break users code, hence the suggestion to deprecate them first.

refactor: Remove internal uses of the `.first()` and `.matchCondition()` helpers

---

src/utils/Utils.ts

Less code both in the source and builds and will be slightly faster at runtime as it doesn't need the private property polyfill.

chore(Utils): Replace private static shim property with a variable

---

protos/generated/misc/params.ts
protos/misc/params.proto
src/Innertube.ts

For some post ID and channel ID combinations the encoded protobuf string can contain `/`, which we need to replace with `_` for proper URL safe base64 (this was causing YouTube to return the channel home page instead of the post page). I also corrected the type of some of the number fields to uint32

fix(Innertube): Properly encoded params in `getPost()`

---

.gitignore
src/parser/classes/AnimatedThumbnailOverlayView.ts
src/parser/classes/ThumbnailView.ts
src/parser/nodes.ts

Add AnimatedThumbnailOverlayView to ThumbnailView. Seem to run into it sporadically on some videos.

feat(parser): Add `AnimatedThumbnailOverlayView`

---

src/utils/StreamingInfo.ts

The issue that #858 aimed to fix only happens on a very small number of issues, as the fix seems to be causing more problems than it fixes (e.g. wrong audio track getting selected by default on videos where the original track does not match the language that was used to make the API request), this pull request proposes to revert that change.

revert: "fix(toDash): Fix default audio stream for dubbed movie trailers (#858)"

---

src/Innertube.ts

Fixes #828 
The function did not use the client parameter while still allowing the user to provide it in Format Options.

fix(innertube): Allowing getStreamingData to use client.

---

protos/generated/misc/common.ts
protos/misc/common.proto
src/parser/classes/misc/Format.ts

As SABR-only responses don't contain the individual URLs for the adaptive formats, parsing the xtags from the URLs is not possible with those reponses. To fix that I have switched to parsing the xtags protobuf instead, which is available on both "normal" responses and SABR-only ones. I have tested this PR on a SABR-only response and various normal reponses for video with multiple audio tracks and the parsed information seemed to be correct.

fix(Format): Parse xtags from protobuf to support SABR-only responses

---

src/utils/Constants.ts
src/utils/HTTPClient.ts

This pull request fixes the "precondition failed" error when requesting the player with the iOS client. YouTube seems to have deprecated the 18.x app version, increasing the rollout yesterday. Thought it'd be better to make a pull request with a fix right away rather than an issue.
This is the latest app version at the time of writing, so it should last a good while.

fix(Constants): Update the iOS client version

---

src/Innertube.ts
src/core/clients/Kids.ts
src/core/clients/Studio.ts
src/utils/HTTPClient.ts

In some methods we were accessing the same private property lots of times. As the private property polyfill results in extra code and runtime overhead for each private property access, in some of those methods I decided to read it into a local variable once at the top of the method and then use that local variable in the other places. While this is probably not a major bottleneck, it doesn't hurt and results in smaller code size which is great for people that are bundling YouTube.js.

refactor(internal): Reduce frequent accesses to the same private property

---

src/parser/classes/MusicResponsiveListItem.ts

Passing `playlist_item_data` as a parameter instead of a private property results in less code as we avoid the private property polyfill code for `playlist_item_data`.

chore(parser): Pass playlist_item_data as a parameter instead of a private property

---

dev-scripts/enum-optimising-transformer.cjs
tsconfig.json

It retains the two-way mappings for numeric enums and follows TypeScripts behaviour of only generating one-way mappings for string enums, it also only handles basic enums so either where no values are assigned or they are static. Currently all enums in the code base fit that criteria, however if an enum were to be added that doesn't, then a warning will be logged and it will fallback to tsc's own enum emit for that enum.
This:
```ts
enum Sample {
Val1,
Val2
}
```
Gets turned into this, instead of TypeScripts complicated output (which they need to support the dynamic enum values), it also allows removing the unused members during bundling if there are no dynamic lookups or removing the entire enum if it is unused.
```js
const Sample = {
Val1 = 0,
0: "Val1",
Val2: 1,
1: "Val2"
}
```
Which …

chore(build): More efficient enum emit

---

package-lock.json
package.json
src/core/Player.ts

This change allows matching code such as:
```
// "Y" is the global var.
r = r[Y[14]](Y[19]);
q3[Y[8]](r, 30);
q3[Y[8]](r, 65);
q3[Y[8]](r, 2);
```
TODO:
Maybe consider removing the regex (it's too fragile) and instead use the AST walker, like we already do for `nsig` and the global lookup variable.
Closes #952

fix(Player): Use global var to find signature algorithm

---

src/Innertube.ts

Same issue that PR #882 solved but for the getPostComments() method.
Example post where getting post comments was failing (but is fixed by this PR): https://www.youtube.com/channel/UCX6OQ3DkcsbYNE6H8uQQuVA/community?lb=UgkxtWKnO2Yc3gxTEWTGylicAK2gv8CSfeAO

fix(Innertube): Properly encoded params in getPostComments()

---

src/Innertube.ts

For `getInfo` YouTube.js sets the `racyCheckOk` and `contentCheckOk` properties to `true` but they are currently not set for `getBasicInfo`. This pull request corrects by adding them to the `getBasicInfo` request too.

fix(getBasicInfo): Add racyCheckOk and contentCheckOk to payload

---

src/core/mixins/MediaInfo.ts
src/types/StreamingInfoOptions.ts
src/utils/StreamingInfo.ts

Returns a manifest suitable for use in SABR player implementations.
NOTE: This changes the signature of `MediaInfo#toDash`, so I consider it a breaking change.
Example:
```ts
// ...
const info = await innertube.getBasicInfo('9Go0dVabZNs');
const manifest = await info.toDash({
manifest_options: {
is_sabr: true
}
});
console.log(manifest);
```

feat(StreamingInfoOptions)!: Add `is_sabr` option

---

src/parser/classes/NavigationEndpoint.ts

YouTube has started occasionally returning CommandExecutorCommands inside of the playlist ContinuationItems, this pull request adds handling for them to fix playlist continuations erroring with `TypeError: command.getApiPath is not a function`.
Related https://github.com/FreeTubeApp/FreeTube/issues/7437, https://github.com/TeamNewPipe/NewPipeExtractor/pull/1301

fix: Handle CommandExecutorCommand in NavigationEndpoint.call

---

src/core/Session.ts

fixes #970 
testing:
---
```
const yt = await Innertube.create({client_type: ClientType.MUSIC});
console.log(yt.session) 
```
before:
shows client.version = 2.xxx which is web's
after:
should show 1.xxx

fix(Session): Initialize client version based on provided client name

---

src/parser/classes/CompositeVideoPrimaryInfo.ts
src/parser/nodes.ts

* Added a new parser class called `CompositeVideoPrimaryInfo`.
<details><summary><strong>Error Message</strong></summary>
```console
[YOUTUBEJS][Parser]: InnertubeError: CompositeVideoPrimaryInfo not found!
This is a bug, want to help us fix it? Follow the instructions at https://github.com/LuanRT/YouTube.js/blob/main/docs/updating-the-parser.md or report it at https://github.com/LuanRT/YouTube.js/issues!
Introspected and JIT generated this class in the meantime:
class CompositeVideoPrimaryInfo extends YTNode {
static type = 'CompositeVideoPrimaryInfo';
constructor(data: RawNode) {
super();
}
}
...
```
</details>

feat(parser-classes): Add `CompositeVideoPrimaryInfo` parser class

---

package-lock.json
package.json
tsconfig.json

Now that the tsconfig target is set to ESNext TypeScript won't generate or import any polyfills, so we no longer need the tslib dependency. For the bundles created with esbuild, esbuild adds its own polyfills.

chore: Remove unused tslib dependency

---

dev-scripts/get-agents.mjs
package-lock.json
package.json
src/platform/node.ts

Now that YouTube.js only support more recent versions of Node.js, we no longer need the external undici dependency and can instead use the fetch implementation built-into Node.js, which is also happens to be undici.

refactor(node): Replace undici dependency with built-in fetch
